# Generated by Django 3.1.3 on 2020-11-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        ('player', '0002_auto_20201128_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.BigIntegerField(default=0, verbose_name='storage_cash')),
                ('oil', models.IntegerField(default=0, verbose_name='oil')),
                ('oil_cap', models.IntegerField(default=100000, verbose_name='Нефть- максимум на складе')),
                ('ore', models.IntegerField(default=0, verbose_name='ore')),
                ('ore_cap', models.IntegerField(default=100000, verbose_name='Руда- максимум на складе')),
                ('gas', models.IntegerField(default=0, verbose_name='gas')),
                ('gas_cap', models.IntegerField(default=10000, verbose_name='Бензин- максимум на складе')),
                ('steel', models.IntegerField(default=0, verbose_name='steel')),
                ('steel_cap', models.IntegerField(default=10000, verbose_name='Сталь- максимум на складе')),
                ('tank', models.IntegerField(default=0, verbose_name='tank')),
                ('tank_cap', models.IntegerField(default=1000, verbose_name='Танки- максимум на складе')),
                ('jet', models.IntegerField(default=0, verbose_name='attack_air')),
                ('jet_cap', models.IntegerField(default=1000, verbose_name='Штурмовики- максимум на складе')),
                ('station', models.IntegerField(default=0, verbose_name='orb_station')),
                ('station_cap', models.IntegerField(default=10, verbose_name='Орбитальные орудия- максимум на складе')),
                ('pzrk', models.IntegerField(default=0, verbose_name='mpads')),
                ('pzrk_cap', models.IntegerField(default=1000, verbose_name='ПЗРК- максимум на складе')),
                ('antitank', models.IntegerField(default=0, verbose_name='antitank')),
                ('antitank_cap', models.IntegerField(default=1000, verbose_name='ПТ-пушка- максимум на складе')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='player.player', verbose_name='Владелец')),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement', to='state.region', verbose_name='Регион размещения')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
    ]
