# Generated by Django 3.1.3 on 2021-01-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='alumunuim',
            new_name='aluminium',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='alumunuim_cap',
            new_name='aluminium_cap',
        ),
    ]
