# Generated by Django 3.1.3 on 2021-01-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20210109_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='aluminium',
            field=models.IntegerField(default=0, verbose_name='alumunuim'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='aluminium_cap',
            field=models.IntegerField(default=10000, verbose_name='alumunuim_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='anohor',
            field=models.IntegerField(default=0, verbose_name='anohor'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='anohor_cap',
            field=models.IntegerField(default=100000, verbose_name='anohor_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='antitank',
            field=models.IntegerField(default=0, verbose_name='antitank'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='antitank_cap',
            field=models.IntegerField(default=1000, verbose_name='ПТ-пушка- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='berkonor',
            field=models.IntegerField(default=0, verbose_name='berkonor'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='berkonor_cap',
            field=models.IntegerField(default=100000, verbose_name='berkonor_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='brent_oil',
            field=models.IntegerField(default=0, verbose_name='brent_oil'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='brent_oil_cap',
            field=models.IntegerField(default=100000, verbose_name='brent_oil_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='cash',
            field=models.BigIntegerField(default=0, verbose_name='storage_cash'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='diesel',
            field=models.IntegerField(default=0, verbose_name='diesel'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='diesel_cap',
            field=models.IntegerField(default=10000, verbose_name='diesel_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='gas',
            field=models.IntegerField(default=0, verbose_name='gas'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='gas_cap',
            field=models.IntegerField(default=10000, verbose_name='gas_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='grokcite',
            field=models.IntegerField(default=0, verbose_name='grokcite'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='grokcite_cap',
            field=models.IntegerField(default=100000, verbose_name='grokcite_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='jet',
            field=models.IntegerField(default=0, verbose_name='attack_air'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='jet_cap',
            field=models.IntegerField(default=1000, verbose_name='Штурмовики- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='pzrk',
            field=models.IntegerField(default=0, verbose_name='mpads'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='pzrk_cap',
            field=models.IntegerField(default=1000, verbose_name='ПЗРК- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='station',
            field=models.IntegerField(default=0, verbose_name='orb_station'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='station_cap',
            field=models.IntegerField(default=10, verbose_name='Орбитальные орудия- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='steel',
            field=models.IntegerField(default=0, verbose_name='steel'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='steel_cap',
            field=models.IntegerField(default=10000, verbose_name='steel_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='tank',
            field=models.IntegerField(default=0, verbose_name='tank'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='tank_cap',
            field=models.IntegerField(default=1000, verbose_name='Танки- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='urals_oil',
            field=models.IntegerField(default=0, verbose_name='urals_oil'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='urals_oil_cap',
            field=models.IntegerField(default=100000, verbose_name='urals_oil_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='wti_oil',
            field=models.IntegerField(default=0, verbose_name='wti_oil'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='wti_oil_cap',
            field=models.IntegerField(default=100000, verbose_name='wti_oil_cap'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('owner', 'region'), name='one_in_region'),
        ),
    ]
