# Generated by Django 3.1.3 on 2021-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20210109_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='anohor',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='anohor_cap',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='berkonor',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='berkonor_cap',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='grokcite',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='grokcite_cap',
        ),
        migrations.AddField(
            model_name='storage',
            name='bauxite',
            field=models.IntegerField(default=0, verbose_name='bauxite'),
        ),
        migrations.AddField(
            model_name='storage',
            name='bauxite_cap',
            field=models.IntegerField(default=100000, verbose_name='bauxite_cap'),
        ),
        migrations.AddField(
            model_name='storage',
            name='coal',
            field=models.IntegerField(default=0, verbose_name='coal'),
        ),
        migrations.AddField(
            model_name='storage',
            name='coal_cap',
            field=models.IntegerField(default=100000, verbose_name='coal_cap'),
        ),
        migrations.AddField(
            model_name='storage',
            name='iron',
            field=models.IntegerField(default=0, verbose_name='iron'),
        ),
        migrations.AddField(
            model_name='storage',
            name='iron_cap',
            field=models.IntegerField(default=100000, verbose_name='iron_cap'),
        ),
    ]
