# Generated by Django 3.1.3 on 2021-02-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='storage_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_to', to='storage.storage', verbose_name='Склад получения'),
        ),
    ]
