# Generated by Django 3.1.3 on 2021-02-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20210212_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='coal',
            field=models.IntegerField(default=0, verbose_name='Уголь'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='storage_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_from', to='storage.storage', verbose_name='Склад отправки'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='storage_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_to', to='storage.storage', verbose_name='Склад получения'),
        ),
    ]
