# Generated by Django 3.1.3 on 2021-02-28 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20201213_1838'),
        ('storage', '0008_auto_20210224_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('coal', models.IntegerField(default=0, verbose_name='Уголь')),
                ('iron', models.IntegerField(default=0, verbose_name='iron')),
                ('bauxite', models.IntegerField(default=0, verbose_name='bauxite')),
                ('wti_oil', models.IntegerField(default=0, verbose_name='wti_oil')),
                ('brent_oil', models.IntegerField(default=0, verbose_name='brent_oil')),
                ('urals_oil', models.IntegerField(default=0, verbose_name='urals_oil')),
                ('gas', models.IntegerField(default=0, verbose_name='gas')),
                ('diesel', models.IntegerField(default=0, verbose_name='diesel')),
                ('steel', models.IntegerField(default=0, verbose_name='steel')),
                ('aluminium', models.IntegerField(default=0, verbose_name='alumunuim')),
                ('tank', models.IntegerField(default=0, verbose_name='tank')),
                ('jet', models.IntegerField(default=0, verbose_name='attack_air')),
                ('station', models.IntegerField(default=0, verbose_name='orb_station')),
                ('pzrk', models.IntegerField(default=0, verbose_name='mpads')),
                ('antitank', models.IntegerField(default=0, verbose_name='antitank')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
                ('storage_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_source', to='storage.storage', verbose_name='Склад отправки')),
            ],
            options={
                'verbose_name': 'Лог уничтожения ресурсов',
                'verbose_name_plural': 'Логи уничтожения',
            },
        ),
    ]
