# Generated by Django 3.1.3 on 2021-02-28 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20201213_1838'),
        ('storage', '0010_transport_delivery_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('cash_value', models.BigIntegerField(default=0, verbose_name='Денег передано')),
                ('good_value', models.BigIntegerField(default=0, verbose_name='Товаров передано')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Лог торговли',
                'verbose_name_plural': 'Логи торговли',
            },
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_volume', models.BigIntegerField(default=0, verbose_name='Количество изначально')),
                ('count', models.BigIntegerField(default=0, verbose_name='Количество')),
                ('price', models.BigIntegerField(default=0, verbose_name='Цена')),
                ('cost', models.BigIntegerField(default=0, verbose_name='Стоимость закупки')),
                ('cost_count', models.BigIntegerField(default=0, verbose_name='Осталось денег в закупке')),
                ('delivery_sum', models.BigIntegerField(default=0, verbose_name='Бюджет доставки')),
                ('delivery_sum_count', models.BigIntegerField(default=0, verbose_name='Осталось денег в бюджете доставки')),
                ('delivery_sum_once', models.BigIntegerField(default=0, verbose_name='За доставку разово')),
                ('type', models.CharField(choices=[('sell', 'Продажа'), ('buy', 'Покупка')], default='sell', max_length=4)),
                ('view_type', models.CharField(choices=[('all', 'Все'), ('state', 'Государство'), ('party', 'party')], default='all', max_length=6)),
                ('good', models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК')], default='sell', max_length=10)),
                ('create_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('accept_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('accepters', models.ManyToManyField(blank=True, related_name='offer_accepters', to='storage.TradingLog', verbose_name='Принявшие ордер')),
                ('owner_storage', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_storage', to='storage.storage', verbose_name='Склад разместившего')),
            ],
            options={
                'verbose_name': 'Торговый ордер',
                'verbose_name_plural': 'Торговые ордера',
            },
        ),
    ]
