# Generated by Django 3.1.3 on 2021-03-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_tradeoffer_tradinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_good', models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК')], default=None, max_length=10)),
                ('lock_count', models.BigIntegerField(default=0, verbose_name='Количество')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('lock_storage', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lock_storage', to='storage.storage', verbose_name='Склад блокировки')),
            ],
            options={
                'verbose_name': 'Блокировка ресурсов',
                'verbose_name_plural': 'Блокировки ресурсов',
            },
        ),
    ]
