# Generated by Django 3.1.3 on 2021-03-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_goodlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodlock',
            name='lock_storage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lock_storage', to='storage.storage', verbose_name='Склад блокировки'),
        ),
    ]
