# Generated by Django 3.1.3 on 2021-03-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20201213_1838'),
        ('storage', '0013_auto_20210309_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_cash', models.BigIntegerField(default=0, verbose_name='Количество')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('lock_player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lock_player', to='player.player', verbose_name='Счет блокировки')),
            ],
            options={
                'verbose_name': 'Блокировка денег',
                'verbose_name_plural': 'Блокировки денег',
            },
        ),
    ]
