# Generated by Django 3.1.3 on 2021-03-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_cashlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeoffer',
            name='delivery_sum',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='delivery_sum_count',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='delivery_sum_once',
        ),
        migrations.AddField(
            model_name='cashlock',
            name='lock_offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lock_offer', to='storage.tradeoffer', verbose_name='Торговое предложение'),
        ),
        migrations.AddField(
            model_name='goodlock',
            name='lock_offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='good_lock_offer', to='storage.tradeoffer', verbose_name='Торговое предложение'),
        ),
    ]
