# Generated by Django 3.1.3 on 2021-03-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_auto_20210309_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='aluminium',
            field=models.IntegerField(default=0, verbose_name='Алюминий'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='aluminium_vol',
            field=models.IntegerField(default=0, verbose_name='Алюминий - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='antitank',
            field=models.IntegerField(default=0, verbose_name='ПТ-пушка'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='antitank_vol',
            field=models.IntegerField(default=0, verbose_name='ПТ-пушка - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='bauxite',
            field=models.IntegerField(default=0, verbose_name='Бокситы'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='brent_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Brent'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='brent_oil_vol',
            field=models.IntegerField(default=0, verbose_name='Brent - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='diesel',
            field=models.IntegerField(default=0, verbose_name='Дизель'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='diesel_vol',
            field=models.IntegerField(default=0, verbose_name='Дизель - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='gas',
            field=models.IntegerField(default=0, verbose_name='Бензин'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='gas_vol',
            field=models.IntegerField(default=0, verbose_name='Бензин - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='iron',
            field=models.IntegerField(default=0, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='jet',
            field=models.IntegerField(default=0, verbose_name='Штурмовики'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='jet_vol',
            field=models.IntegerField(default=0, verbose_name='Штурмовики - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='pzrk',
            field=models.IntegerField(default=0, verbose_name='ПЗРК'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='pzrk_vol',
            field=models.IntegerField(default=0, verbose_name='ПЗРК - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='station',
            field=models.IntegerField(default=0, verbose_name='Орбиталки'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='station_vol',
            field=models.IntegerField(default=0, verbose_name='Орбиталки - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='steel',
            field=models.IntegerField(default=0, verbose_name='Сталь'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='steel_vol',
            field=models.IntegerField(default=0, verbose_name='Сталь - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='tank',
            field=models.IntegerField(default=0, verbose_name='Танки'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='tank_vol',
            field=models.IntegerField(default=0, verbose_name='Танки - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='urals_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Urals'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='urals_oil_vol',
            field=models.IntegerField(default=0, verbose_name='Urals - кубов'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='wti_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть WTI'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='wti_oil_vol',
            field=models.IntegerField(default=0, verbose_name='WTI - кубов'),
        ),
    ]
