# Generated by Django 3.1.3 on 2021-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_auto_20210312_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
