# Generated by Django 3.1.3 on 2021-07-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_storage_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinglog',
            name='accepter_storage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepter_storage', to='storage.storage', verbose_name='Склад принявшего оффер'),
        ),
        migrations.AddField(
            model_name='tradinglog',
            name='delivery_value',
            field=models.BigIntegerField(default=0, verbose_name='Стоимость доставки'),
        ),
    ]
