# Generated by Django 3.1.3 on 2021-09-16 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_chat_ban'),
        ('storage', '0019_auto_20210718_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('prod_result', models.CharField(max_length=50, verbose_name='Продукция')),
                ('cash', models.BigIntegerField(default=0, verbose_name='storage_cash')),
                ('coal', models.IntegerField(default=0, verbose_name='Уголь')),
                ('iron', models.IntegerField(default=0, verbose_name='iron')),
                ('bauxite', models.IntegerField(default=0, verbose_name='bauxite')),
                ('wti_oil', models.IntegerField(default=0, verbose_name='wti_oil')),
                ('brent_oil', models.IntegerField(default=0, verbose_name='brent_oil')),
                ('urals_oil', models.IntegerField(default=0, verbose_name='urals_oil')),
                ('gas', models.IntegerField(default=0, verbose_name='gas')),
                ('diesel', models.IntegerField(default=0, verbose_name='diesel')),
                ('steel', models.IntegerField(default=0, verbose_name='steel')),
                ('aluminium', models.IntegerField(default=0, verbose_name='alumunuim')),
                ('tank', models.IntegerField(default=0, verbose_name='tank')),
                ('jet', models.IntegerField(default=0, verbose_name='attack_air')),
                ('station', models.IntegerField(default=0, verbose_name='orb_station')),
                ('pzrk', models.IntegerField(default=0, verbose_name='mpads')),
                ('antitank', models.IntegerField(default=0, verbose_name='antitank')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
                ('prod_storage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_storage', to='storage.storage', verbose_name='Склад производства')),
            ],
            options={
                'verbose_name': 'Лог производства',
                'verbose_name_plural': 'Логи производства',
            },
        ),
    ]
