# Generated by Django 3.1.3 on 2021-10-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_productionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='was_moved',
            field=models.BooleanField(default=False, verbose_name='Переносился'),
        ),
    ]
