# Generated by Django 3.1.3 on 2021-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_storage_was_moved'),
    ]

    operations = [
        migrations.AddField(
            model_name='destroy',
            name='rifle',
            field=models.IntegerField(default=0, verbose_name='Автоматы'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='rifle',
            field=models.IntegerField(default=0, verbose_name='rifle'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rifle',
            field=models.IntegerField(default=0, verbose_name='Автоматы'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rifle_cap',
            field=models.IntegerField(default=1000, verbose_name='Автоматы- максимум на складе'),
        ),
        migrations.AddField(
            model_name='transport',
            name='rifle',
            field=models.IntegerField(default=0, verbose_name='Автоматы'),
        ),
        migrations.AddField(
            model_name='transport',
            name='rifle_vol',
            field=models.IntegerField(default=0, verbose_name='Автоматы - кубов'),
        ),
    ]
