# Generated by Django 3.1.3 on 2021-10-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_auto_20211023_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='destroy',
            name='howitzer',
            field=models.IntegerField(default=0, verbose_name='howitzer'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='howitzer',
            field=models.IntegerField(default=0, verbose_name='howitzer'),
        ),
        migrations.AddField(
            model_name='storage',
            name='howitzer',
            field=models.IntegerField(default=0, verbose_name='Гаубицы'),
        ),
        migrations.AddField(
            model_name='storage',
            name='howitzer_cap',
            field=models.IntegerField(default=1000, verbose_name='Гаубицы- максимум на складе'),
        ),
        migrations.AddField(
            model_name='transport',
            name='howitzer',
            field=models.IntegerField(default=0, verbose_name='Гаубица'),
        ),
        migrations.AddField(
            model_name='transport',
            name='howitzer_vol',
            field=models.IntegerField(default=0, verbose_name='Гаубица - кубов'),
        ),
        migrations.AlterField(
            model_name='goodlock',
            name='lock_good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('howitzer', 'Гаубица')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('howitzer', 'Гаубицы')], default='sell', max_length=10),
        ),
    ]
