# Generated by Django 3.1.3 on 2021-10-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_auto_20211023_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destroy',
            name='howitzer',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='howitzer',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='howitzer_cap',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='howitzer',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='howitzer_vol',
        ),
        migrations.AddField(
            model_name='destroy',
            name='ifv',
            field=models.IntegerField(default=0, verbose_name='ifv'),
        ),
        migrations.AddField(
            model_name='storage',
            name='ifv',
            field=models.IntegerField(default=0, verbose_name='БМП'),
        ),
        migrations.AddField(
            model_name='storage',
            name='ifv_cap',
            field=models.IntegerField(default=1000, verbose_name='БМП- максимум на складе'),
        ),
        migrations.AddField(
            model_name='transport',
            name='ifv',
            field=models.IntegerField(default=0, verbose_name='БМП'),
        ),
        migrations.AddField(
            model_name='transport',
            name='ifv_vol',
            field=models.IntegerField(default=0, verbose_name='БМП - кубов'),
        ),
        migrations.AlterField(
            model_name='goodlock',
            name='lock_good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='storage',
            name='rifle_cap',
            field=models.IntegerField(default=10000, verbose_name='Автоматы- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП')], default='sell', max_length=10),
        ),
    ]
