# Generated by Django 3.1.3 on 2021-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0024_auto_20211031_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlog',
            name='howitzer',
        ),
        migrations.AddField(
            model_name='productionlog',
            name='ifv',
            field=models.IntegerField(default=0, verbose_name='ifv'),
        ),
    ]
