# Generated by Django 3.1.3 on 2021-12-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0025_auto_20211031_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='destroy',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Койки'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Койки'),
        ),
        migrations.AddField(
            model_name='storage',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Койки'),
        ),
        migrations.AddField(
            model_name='storage',
            name='medical_cap',
            field=models.IntegerField(default=10000, verbose_name='medical_cap'),
        ),
        migrations.AddField(
            model_name='transport',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Койки'),
        ),
        migrations.AddField(
            model_name='transport',
            name='medical_vol',
            field=models.IntegerField(default=0, verbose_name='Койки - кубов'),
        ),
        migrations.AlterField(
            model_name='goodlock',
            name='lock_good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Койки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Койки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП')], default='sell', max_length=10),
        ),
    ]
