# Generated by Django 3.1.3 on 2021-12-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0029_auto_20211219_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество в лоте')),
                ('start_price', models.IntegerField(default=0, verbose_name='Начальная цена')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('auction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='storage.buyauction', verbose_name='Аукцион')),
            ],
            options={
                'verbose_name': 'Лот аукциона',
                'verbose_name_plural': 'Лоты аукционов',
            },
        ),
    ]
