# Generated by Django 3.1.3 on 2021-12-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0030_auctionlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlot',
            name='win_storage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_storage', to='storage.storage', verbose_name='Склад победителя'),
        ),
        migrations.AlterField(
            model_name='goodlock',
            name='lock_offer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_lock_offer', to='storage.tradeoffer', verbose_name='Торговое предложение'),
        ),
        migrations.CreateModel(
            name='AuctionBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Начальная цена')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('auction_lot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction_lot', to='storage.auctionlot', verbose_name='Лот')),
                ('good_lock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='good_lock', to='storage.goodlock', verbose_name='Блокировка Склада')),
            ],
            options={
                'verbose_name': 'Ставка аукциона',
                'verbose_name_plural': 'Ставки аукционов',
            },
        ),
    ]
