# Generated by Django 3.1.3 on 2021-12-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0031_auto_20211220_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbet',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Текущая цена'),
        ),
    ]
