# Generated by Django 3.1.3 on 2022-08-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0034_auto_20220501_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='drone',
            field=models.IntegerField(default=0, verbose_name='Дроны'),
        ),
        migrations.AddField(
            model_name='storage',
            name='drone_cap',
            field=models.IntegerField(default=1000, verbose_name='Дроны- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='buyauction',
            name='good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Койки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'Дроны')], default='coal', max_length=10, verbose_name='Товар'),
        ),
    ]
