# Generated by Django 3.1.3 on 2022-08-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0035_auto_20220806_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='destroy',
            name='drone',
            field=models.IntegerField(default=0, verbose_name='Дроны'),
        ),
        migrations.AddField(
            model_name='transport',
            name='drone',
            field=models.IntegerField(default=0, verbose_name='Дроны'),
        ),
        migrations.AddField(
            model_name='transport',
            name='drone_vol',
            field=models.IntegerField(default=0, verbose_name='Дроны - кубов'),
        ),
        migrations.AlterField(
            model_name='goodlock',
            name='lock_good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Койки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'Дроны')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Койки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'Дроны'), ('wild_pass', 'Wild Pass')], default='sell', max_length=10),
        ),
    ]
