# Generated by Django 3.1.3 on 2022-09-25 11:52

from django.db import migrations


def create_test_storages(apps, schema_editor):

    Storage = apps.get_model("storage", "Storage")
    Player = apps.get_model("player", "Player")
    Region = apps.get_model("region", "Region")
    
    piter = Region.with_off.get(pk=12)
    players = Player.objects.all()

    for player in players:
    
        if not Storage.objects.filter(owner=player, region=piter).exists():                
    
            Storage.objects.create(
                                    owner=player,
                                    region=piter,
                                    rifle=10000,
                                    tank=10000,
                                    antitank=10000,
                                    jet=10000,
                                    pzrk=10000,
                                    ifv=10000,
                                    drone=10000,
                                   )


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0038_auto_20220828_1627'),
    ]

    operations = [
            migrations.RunPython(create_test_storages),
    ]
