# Generated by Django 3.1.3 on 2022-11-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0041_auto_20221109_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='aluminium_cap',
            field=models.IntegerField(default=1000, verbose_name='alumunuim_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='antitank_cap',
            field=models.IntegerField(default=100, verbose_name='ПТ-пушка- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='bauxite_cap',
            field=models.IntegerField(default=10000, verbose_name='bauxite_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='brent_oil_cap',
            field=models.IntegerField(default=10000, verbose_name='brent_oil_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='coal_cap',
            field=models.IntegerField(default=10000, verbose_name='coal_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='diesel_cap',
            field=models.IntegerField(default=1000, verbose_name='diesel_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='drone_cap',
            field=models.IntegerField(default=100, verbose_name='Дроны- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='gas_cap',
            field=models.IntegerField(default=1000, verbose_name='gas_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='ifv_cap',
            field=models.IntegerField(default=100, verbose_name='БМП- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='iron_cap',
            field=models.IntegerField(default=10000, verbose_name='iron_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='jet_cap',
            field=models.IntegerField(default=100, verbose_name='Штурмовики- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='medical_cap',
            field=models.IntegerField(default=1000, verbose_name='medical_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='plastic_cap',
            field=models.IntegerField(default=1000, verbose_name='plastic_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='pzrk_cap',
            field=models.IntegerField(default=100, verbose_name='ПЗРК- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='rifle_cap',
            field=models.IntegerField(default=1000, verbose_name='Автоматы- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='steel_cap',
            field=models.IntegerField(default=1000, verbose_name='steel_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='tank_cap',
            field=models.IntegerField(default=100, verbose_name='Танки- максимум на складе'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='urals_oil_cap',
            field=models.IntegerField(default=10000, verbose_name='urals_oil_cap'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='wti_oil_cap',
            field=models.IntegerField(default=10000, verbose_name='wti_oil_cap'),
        ),
    ]
