# Generated by Django 3.1.3 on 2022-11-27 17:18

from django.db import migrations

def shrink_storages(apps, schema_editor):

    Storage = apps.get_model("storage", "Storage")
    
    storages = Storage.objects.update(
        coal_cap=10000,
        iron_cap=10000,
        bauxite_cap=10000,
        wti_oil_cap=10000,
        brent_oil_cap=10000,
        urals_oil_cap=10000,
        
        gas_cap=1000,
        diesel_cap=1000,
        plastic_cap=1000,
        steel_cap=1000,
        aluminium_cap=1000,
        medical_cap=1000,
        rifle_cap=1000,
        
        antitank_cap=100,
        tank_cap=100,
        jet_cap=100,
        pzrk_cap=100,
        ifv_cap=100,
        drone_cap=100,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0042_auto_20221127_1737'),
    ]

    operations = [
        migrations.RunPython(shrink_storages),
    ]
