# Generated by Django 3.1.3 on 2022-11-27 17:27

from django.db import migrations

def material_storages(apps, schema_editor):

    Storage = apps.get_model("storage", "Storage")
    Player = apps.get_model("player", "Player")
    Region = apps.get_model("region", "Region")

    players = Player.objects.all()

    for player in players:
    
        storages = Storage.objects.filter(owner=player).order_by('pk')
        
        count = 1
        for storage in storages:
            if count == 1:
                count += 1
                continue
            
            storage.steel += ( count * 500 ) - 500
            storage.aluminium += ( count * 500 ) - 500
            storage.save()
            
            count += 1
    
        



class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0044_auto_20221127_2018'),
    ]

    operations = [
        migrations.RunPython(material_storages),
    ]
