# Generated by Django 3.1.3 on 2022-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0045_auto_20221127_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyauction',
            name='good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'БПЛА')], default='coal', max_length=10, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='aluminium',
            field=models.IntegerField(default=0, verbose_name='Алюминий'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='antitank',
            field=models.IntegerField(default=0, verbose_name='ПТ-орудия'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='bauxite',
            field=models.IntegerField(default=0, verbose_name='Бокситы'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='brent_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Brent'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='diesel',
            field=models.IntegerField(default=0, verbose_name='Дизельное топливо'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='drone',
            field=models.IntegerField(default=0, verbose_name='БПЛА'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='gas',
            field=models.IntegerField(default=0, verbose_name='Бензин'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='ifv',
            field=models.IntegerField(default=0, verbose_name='БМП'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='iron',
            field=models.IntegerField(default=0, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='jet',
            field=models.IntegerField(default=0, verbose_name='Штурмовики'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Медикаменты'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='plastic',
            field=models.IntegerField(default=0, verbose_name='Пластик'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='pzrk',
            field=models.IntegerField(default=0, verbose_name='ПЗРК'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='station',
            field=models.IntegerField(default=0, verbose_name='Орбитальные орудия'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='steel',
            field=models.IntegerField(default=0, verbose_name='Сталь'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='tank',
            field=models.IntegerField(default=0, verbose_name='Танки'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='urals_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Urals'),
        ),
        migrations.AlterField(
            model_name='destroy',
            name='wti_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть WTI'),
        ),
        migrations.AlterField(
            model_name='goodlock',
            name='lock_good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'Дроны')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='aluminium',
            field=models.IntegerField(default=0, verbose_name='Алюминий'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='antitank',
            field=models.IntegerField(default=0, verbose_name='ПТ-орудия'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='bauxite',
            field=models.IntegerField(default=0, verbose_name='Бокситы'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='brent_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Brent'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='coal',
            field=models.IntegerField(default=0, verbose_name='Наличные'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='diesel',
            field=models.IntegerField(default=0, verbose_name='Дизельное топливо'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='gas',
            field=models.IntegerField(default=0, verbose_name='Бензин'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='ifv',
            field=models.IntegerField(default=0, verbose_name='БМП'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='iron',
            field=models.IntegerField(default=0, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='jet',
            field=models.IntegerField(default=0, verbose_name='Штурмовики'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Медикаменты'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='plastic',
            field=models.IntegerField(default=0, verbose_name='Пластик'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='pzrk',
            field=models.IntegerField(default=0, verbose_name='ПЗРК'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='rifle',
            field=models.IntegerField(default=0, verbose_name='Автоматы'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='station',
            field=models.IntegerField(default=0, verbose_name='Орбитальные орудия'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='steel',
            field=models.IntegerField(default=0, verbose_name='Сталь'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='tank',
            field=models.IntegerField(default=0, verbose_name='Танки'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='urals_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Urals'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='wti_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть WTI'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='aluminium',
            field=models.IntegerField(default=0, verbose_name='Алюминий'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='aluminium_cap',
            field=models.IntegerField(default=1000, verbose_name='Алюминий - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='antitank',
            field=models.IntegerField(default=0, verbose_name='ПТ-орудия'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='antitank_cap',
            field=models.IntegerField(default=100, verbose_name='ПТ-орудия - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='bauxite',
            field=models.IntegerField(default=0, verbose_name='Бокситы'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='bauxite_cap',
            field=models.IntegerField(default=10000, verbose_name='Бокситы - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='brent_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Brent'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='brent_oil_cap',
            field=models.IntegerField(default=10000, verbose_name='Нефть Brent - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='cash',
            field=models.BigIntegerField(default=0, verbose_name='Наличные'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='coal_cap',
            field=models.IntegerField(default=10000, verbose_name='Уголь - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='diesel',
            field=models.IntegerField(default=0, verbose_name='Дизельное топливо'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='diesel_cap',
            field=models.IntegerField(default=1000, verbose_name='Дизельное топливо - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='drone',
            field=models.IntegerField(default=0, verbose_name='БПЛА'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='drone_cap',
            field=models.IntegerField(default=100, verbose_name='БПЛА - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='gas',
            field=models.IntegerField(default=0, verbose_name='Бензин'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='gas_cap',
            field=models.IntegerField(default=1000, verbose_name='Бензин - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='ifv_cap',
            field=models.IntegerField(default=100, verbose_name='БМП - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='iron',
            field=models.IntegerField(default=0, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='iron_cap',
            field=models.IntegerField(default=10000, verbose_name='Железо - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='jet',
            field=models.IntegerField(default=0, verbose_name='Штурмовики'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='jet_cap',
            field=models.IntegerField(default=100, verbose_name='Штурмовики - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Медикаменты'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='medical_cap',
            field=models.IntegerField(default=1000, verbose_name='Медикаменты - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='plastic',
            field=models.IntegerField(default=0, verbose_name='Пластик'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='plastic_cap',
            field=models.IntegerField(default=1000, verbose_name='Пластик - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='pzrk',
            field=models.IntegerField(default=0, verbose_name='ПЗРК'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='pzrk_cap',
            field=models.IntegerField(default=100, verbose_name='ПЗРК - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='rifle_cap',
            field=models.IntegerField(default=1000, verbose_name='Автоматы - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='station',
            field=models.IntegerField(default=0, verbose_name='Орбитальные орудия'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='station_cap',
            field=models.IntegerField(default=10, verbose_name='Орбитальные орудия - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='steel',
            field=models.IntegerField(default=0, verbose_name='Сталь'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='steel_cap',
            field=models.IntegerField(default=1000, verbose_name='Сталь - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='tank',
            field=models.IntegerField(default=0, verbose_name='Танки'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='tank_cap',
            field=models.IntegerField(default=100, verbose_name='Танки - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='urals_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Urals'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='urals_oil_cap',
            field=models.IntegerField(default=10000, verbose_name='Нефть Urals - лимит'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='wti_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть WTI'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='wti_oil_cap',
            field=models.IntegerField(default=10000, verbose_name='Нефть WTI - лимит'),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'БПЛА'), ('wild_pass', 'Wild Pass')], default='sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Медикаменты'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='medical_vol',
            field=models.IntegerField(default=0, verbose_name='Медикаменты - кубов'),
        ),
    ]
