# Generated by Django 3.1.3 on 2023-01-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    database_operations = [migrations.AlterModelTable('ProductionLog', 'factory_productionlog')]
    
    state_operations = [migrations.DeleteModel('ProductionLog')]

    dependencies = [
        ('storage', '0046_auto_20221204_0105'),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
