# Generated by Django 3.1.3 on 2023-01-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0047_auto_20230112_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='drilling',
            field=models.IntegerField(default=0, verbose_name='Буровое оборудование'),
        ),
        migrations.AddField(
            model_name='storage',
            name='drilling_cap',
            field=models.IntegerField(default=1000, verbose_name='Буры - лимит'),
        ),
        migrations.AlterField(
            model_name='buyauction',
            name='good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('drilling', 'Буровое оборудование'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'БПЛА')], default='coal', max_length=10, verbose_name='Товар'),
        ),
    ]
