# Generated by Django 3.1.3 on 2023-05-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0051_auto_20230330_1048'),
    ]

    operations = [       
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_de', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_be', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_es', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_pl', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_tr', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_ind', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_lv', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('name_pt_br', models.CharField(max_length=30, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
