# Generated by Django 3.1.3 on 2023-05-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0052_auto_20230503_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Запас')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар')),
                ('stock_storage', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Запас',
                'verbose_name_plural': 'Запасы',
            },
        ),
    ]
