# Generated by Django 3.1.3 on 2023-05-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0053_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='size',
            field=models.CharField(choices=[('large', 'Большой'), ('medium', 'Средний'), ('small', 'Малый')], default='large', max_length=6),
        ),
    ]
