# Generated by Django 3.1.3 on 2023-05-05 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0054_good_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='large_cap',
            field=models.IntegerField(default=120000, verbose_name='Большой лимит'),
        ),
        migrations.AddField(
            model_name='storage',
            name='medium_cap',
            field=models.IntegerField(default=20000, verbose_name='Средний лимит'),
        ),
        migrations.AddField(
            model_name='storage',
            name='small_cap',
            field=models.IntegerField(default=2000, verbose_name='Малый лимит'),
        ),
    ]
