# Generated by Django 3.1.3 on 2023-05-05 23:10

from django.db import migrations


class Migration(migrations.Migration):
        
    def remove_locks(apps, schema_editor):
        GoodLock = apps.get_model('storage', 'GoodLock')
        Good = apps.get_model('storage', 'Good')
        Stock = apps.get_model('storage', 'Stock')
        
        for lock in GoodLock.objects.filter(deleted=False):
            
            if not Good.objects.filter(name=lock.get_lock_good_display()).exists():
                good = Good(
                            name=lock.get_lock_good_display(),
                            name_ru=lock.get_lock_good_display()
                            )
                good.save()
                
            if not Stock.objects.filter(stock_storage=lock.lock_storage, good=Good.objects.get(name=lock.get_lock_good_display())).exists():
                stock = Stock(stock_storage=lock.lock_storage,
                              good=Good.objects.get(name=lock.get_lock_good_display()),
                              stock=lock.lock_count
                             )
                stock.save()
            else:
                stock = Stock.objects.get(stock_storage=lock.lock_storage, good=Good.objects.get(name=lock.get_lock_good_display()))
                stock.stock += lock.lock_count
                stock.save()
                
        
        TradeOffer = apps.get_model('storage', 'TradeOffer')
        Player = apps.get_model('player', 'Player')

        for offer in TradeOffer.objects.filter(deleted=False, good='wild_pass'):
            player = Player.objects.get(pk=offer.owner_storage.owner.pk)
            player.cards_count += offer.count
            player.save()

        
        TradeOffer.objects.all().delete()
        GoodLock.objects.all().delete()
                
            
    dependencies = [
        ('storage', '0055_auto_20230506_0144'),
    ]

    operations = [
            migrations.RunPython(remove_locks),
    ]
