# Generated by Django 3.1.3 on 2023-05-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0057_auto_20230506_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_storage',
            new_name='storage',
        ),
    ]
