# Generated by Django 3.1.3 on 2023-05-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0058_auto_20230506_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodlock',
            name='old_good',
            field=models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('drilling', 'Буровые установки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('mines', 'Мины'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'Дроны')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='goodlock',
            name='lock_good',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lock_good', to='storage.good', verbose_name='Товар'),
        ),
    ]
