# Generated by Django 3.1.3 on 2023-05-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    def up_storages(apps, schema_editor):
        Storage = apps.get_model('storage', 'Storage')

        for storage in Storage.objects.filter(deleted=False):
            storage.large_cap = storage.level * 120000
            storage.medium_cap = storage.level * 20000
            storage.small_cap = storage.level * 2000

            storage.save()

    dependencies = [
        ('storage', '0059_auto_20230506_0322'),
    ]

    operations = [
        migrations.RunPython(up_storages),
    ]
