# Generated by Django 3.1.3 on 2023-07-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0060_auto_20230506_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='volume',
            field=models.FloatField(default=1, verbose_name='Объём, шт.'),
        ),
    ]
