# Generated by Django 3.1.3 on 2023-07-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    def move_volumes(apps, schema_editor):
        Good = apps.get_model('storage', 'Good')
        Storage = apps.get_model('storage', 'Storage')
        Transport = apps.get_model('storage', 'Transport')
        GoodLock = apps.get_model('storage', 'GoodLock')

        # ------vvvvvvv------Минералы на складе------vvvvvvv------
        minerals = {
            # Уголь
            'coal': 0.007,
            # Железо
            'iron': 0.005,
            # Бокситы
            'bauxite': 0.003,
        }
        # ------vvvvvvv------Нефть на складе------vvvvvvv------
        oils = {
            'wti_oil': 0.1,

            'brent_oil': 0.1,

            'urals_oil': 0.1,
        }
        # ------vvvvvvv------Материалы на складе------vvvvvvv------
        materials = {
            'gas': 0.1,

            'diesel': 0.1,

            'plastic': 0.2,

            # 'steel': 10,
            'steel': 1,

            'aluminium': 1,
            # 'aluminium': 10,
        }
        # ------vvvvvvv------Оборудование на складе------vvvvvvv------
        equipments = {
            # 'medical': 5,
            'medical': 0.5,
            'drilling': 2,
        }
        # ------vvvvvvv------Юниты на складе------vvvvvvv------
        units = {
            'rifle': 0.5,

            # 'tank': 105,
            'tank': 10.5,
            'antitank': 5,
            # 'antitank': 50,
            'mines': 4,
            # 'antitank': 50,

            # 'jet': 150,
            'jet': 15,
            # 'pzrk': 50,
            'pzrk': 5,

            'ifv': 4,
            # 'ifv': 40,

            'drone': 1,
            # 'ifv': 10,
        }

        lock = GoodLock()
        storage = Storage()

        for cat in ['minerals', 'oils', 'materials', 'equipments', 'units']:
            for good in locals().get(cat).keys():
                lock.old_good = good
                Good.objects.filter(name=lock.get_old_good_display()).update(volume=locals().get(cat)[good])


    dependencies = [
        ('storage', '0061_good_volume'),
    ]

    operations = [
        migrations.RunPython(move_volumes),
    ]
