# Generated by Django 3.1.3 on 2023-07-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0062_auto_20230704_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='transport',
            name='good',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар'),
        ),
    ]
