# Generated by Django 3.1.3 on 2023-07-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0064_auto_20230714_0027'),
        ('storage', '0052_auctionbet_dtime'),
    ]

    operations = [
    ]
