# Generated by Django 3.1.3 on 2023-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0065_merge_20230715_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='name_az',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='good',
            name='type',
            field=models.CharField(choices=[('minerals', 'Минералы'), ('oils', 'Нефть'), ('materials', 'Материалы'), ('equipments', 'Оборудование'), ('units', 'Оружие')], default='minerals', max_length=10),
        ),
    ]
