# Generated by Django 3.1.3 on 2023-07-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0067_auto_20230715_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeoffer',
            old_name='good',
            new_name='old_good',
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offer_good',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар'),
        ),
    ]
