# Generated by Django 3.1.3 on 2023-07-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0068_auto_20230720_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodlock',
            name='old_good',
            field=models.CharField(blank=True, choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('drilling', 'Буровые установки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('mines', 'Мины'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'Дроны')], default=None, max_length=10, null=True),
        ),
    ]
