# Generated by Django 3.1.3 on 2023-07-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0069_auto_20230722_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='offer_good',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар'),
        ),
    ]
