# Generated by Django 3.1.3 on 2023-09-14 19:23

from django.db import migrations
from django.utils import translation
from django.utils.translation import gettext_lazy, pgettext_lazy, ugettext as _


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0072_auto_20230903_1430'),
    ]

    operations = [
    ]
