# Generated by Django 3.1.3 on 2023-09-14 19:42

from django.db import migrations
from django.utils import translation
from django.utils.translation import gettext_lazy, pgettext_lazy, ugettext as _


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0073_auto_20230914_2223'),
    ]

    operations = [

    ]
