# Generated by Django 3.1.3 on 2024-05-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0078_lootboxprize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lootboxprize',
            name='gold',
        ),
    ]
