# Generated by Django 3.1.3 on 2024-05-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0079_remove_lootboxprize_gold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lootboxprize',
            options={'verbose_name': 'Наградные самолёты', 'verbose_name_plural': 'Наградные самолёты'},
        ),
        migrations.AddField(
            model_name='lootboxprize',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
