# Generated by Django 3.1.3 on 2024-05-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0080_auto_20240530_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootboxprize',
            name='replaced',
            field=models.BooleanField(default=False, verbose_name='Заменено'),
        ),
    ]
