# Generated by Django 3.1.3 on 2024-06-02 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0076_auto_20240602_1907'),
        ('storage', '0082_auto_20240601_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lootboxprize',
            name='plane',
            field=models.CharField(choices=[('nagger', 'Nagger'), ('pretender', 'Pretender'), ('trickster', 'Trickster'), ('smuggler', 'Smuggler'), ('chaser', 'Chaser'), ('reaper', 'Reaper'), ('cheater', 'Cheater'), ('carrier', 'Carrier'), ('observer', 'Observer'), ('striker', 'Striker'), ('demolisher', 'Demolisher'), ('sprinter', 'Sprinter'), ('harrier', 'Harrier'), ('sailor', 'Sailor'), ('hammer', 'Hammer'), ('beluzzo', 'Диск Белуццо')], max_length=10),
        ),
        migrations.CreateModel(
            name='LootboxCoauthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Комиссия соавтора')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Со-автор')),
            ],
            options={
                'verbose_name': 'Комиссия соавтора',
                'verbose_name_plural': 'Комиссия соавторов',
            },
        ),
    ]
