# Generated by Django 3.1.3 on 2024-06-19 18:43

from django.db import migrations
from math import floor


class Migration(migrations.Migration):

    def give_money(apps, schema_editor):
        Player = apps.get_model('player', 'Player')
        Storage = apps.get_model('storage', 'Storage')
        Stock = apps.get_model('storage', 'Stock')
        Blueprint = apps.get_model('factory', 'Blueprint')
        
        
        
        for player in Player.objects.all():
            cash_add = 0
        
            storages = Storage.objects.filter(owner=player)
            
            stocks = Stock.objects.filter(storage__in=storages)
            
            for stock in stocks:
                if Blueprint.objects.filter(good=stock.good).exists():
                    
                    bp = Blueprint.objects.filter(good=stock.good).order_by('-cash_cost')[0]
                
                    cash_add += floor(bp.cash_cost / 2) * stock.stock
            
            player.cash += cash_add
            player.save()


    dependencies = [
        ('storage', '0086_auto_20240619_1226'),
    ]

    operations = [
        migrations.RunPython(give_money),
    ]
