# Generated by Django 3.2.18 on 2024-09-14 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0087_auto_20240619_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootboxprize',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 13, 12, 0), verbose_name='Дата выпадения'),
        ),
    ]
