# Generated by Django 3.2.18 on 2024-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0091_alter_lootboxprize_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='good',
            name='name_it',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='good',
            name='name_sr',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
    ]
