# Generated by Django 3.2.18 on 2024-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0092_auto_20241028_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Название'),
        ),
    ]
