# Generated by Django 3.1.3 on 2023-01-12 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0040_auto_20221217_1824'),
        ('storage', '0047_auto_20230112_2234'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('prod_result', models.CharField(max_length=50, verbose_name='Продукция')),
                ('cash', models.BigIntegerField(default=0, verbose_name='storage_cash')),
                ('coal', models.IntegerField(default=0, verbose_name='Наличные')),
                ('iron', models.IntegerField(default=0, verbose_name='Железо')),
                ('bauxite', models.IntegerField(default=0, verbose_name='Бокситы')),
                ('wti_oil', models.IntegerField(default=0, verbose_name='Нефть WTI')),
                ('brent_oil', models.IntegerField(default=0, verbose_name='Нефть Brent')),
                ('urals_oil', models.IntegerField(default=0, verbose_name='Нефть Urals')),
                ('gas', models.IntegerField(default=0, verbose_name='Бензин')),
                ('diesel', models.IntegerField(default=0, verbose_name='Дизельное топливо')),
                ('plastic', models.IntegerField(default=0, verbose_name='Пластик')),
                ('steel', models.IntegerField(default=0, verbose_name='Сталь')),
                ('aluminium', models.IntegerField(default=0, verbose_name='Алюминий')),
                ('medical', models.IntegerField(default=0, verbose_name='Медикаменты')),
                ('rifle', models.IntegerField(default=0, verbose_name='Автоматы')),
                ('tank', models.IntegerField(default=0, verbose_name='Танки')),
                ('jet', models.IntegerField(default=0, verbose_name='Штурмовики')),
                ('station', models.IntegerField(default=0, verbose_name='Орбитальные орудия')),
                ('pzrk', models.IntegerField(default=0, verbose_name='ПЗРК')),
                ('antitank', models.IntegerField(default=0, verbose_name='ПТ-орудия')),
                ('ifv', models.IntegerField(default=0, verbose_name='БМП')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
                ('prod_storage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_storage', to='storage.storage', verbose_name='Склад производства')),
            ],
            options={
                'verbose_name': 'Лог производства',
                'verbose_name_plural': 'Логи производства',
                'db_table': 'factory_productionlog',
            },
            bases=(models.Model,),
        ),
    ]
    
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]