# Generated by Django 3.1.3 on 2023-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlog',
            name='aluminium',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='antitank',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='bauxite',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='brent_oil',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='coal',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='diesel',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='ifv',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='jet',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='plastic',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='prod_result',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='pzrk',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='rifle',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='station',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='steel',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='tank',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='urals_oil',
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='wti_oil',
        ),
        migrations.AddField(
            model_name='productionlog',
            name='good',
            field=models.CharField(choices=[('cash', 'Наличные'), ('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'БПЛА')], default=None, max_length=20, verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='good_move',
            field=models.CharField(choices=[('incom', 'Приход'), ('outcm', 'Расход')], default='incom', max_length=5, verbose_name='Тип движения'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='prod_value',
            field=models.IntegerField(default=1, verbose_name='Объем строительства'),
        ),
        migrations.AlterModelTable(
            name='productionlog',
            table=None,
        ),
    ]
