# Generated by Django 3.1.3 on 2023-01-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0040_auto_20221217_1824'),
        ('region', '0026_auto_20221127_1737'),
        ('factory', '0002_auto_20230115_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/factories/', verbose_name='Изображение')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Владелец')),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_place', to='region.region', verbose_name='Регион размещения')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
            },
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='prod_value',
            field=models.IntegerField(default=1, verbose_name='Объем производства'),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(choices=[('gas', 'Бензин'), ('diesel', 'Дизель'), ('plastic', 'Дизель'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Алюминий'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('antitank', 'ПТ-орудия'), ('ifv', 'БМП'), ('drone', 'БПЛА')], default=None, max_length=20, verbose_name='Товар')),
                ('factory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='factory.factory', verbose_name='Фабрика')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
            },
        ),
    ]
