# Generated by Django 3.1.3 on 2023-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_auto_20230115_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='prod_value',
            field=models.IntegerField(default=1, verbose_name='Объем производства'),
        ),
    ]
