# Generated by Django 3.1.3 on 2023-01-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20230115_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Цех', 'verbose_name_plural': 'Цеха'},
        ),
    ]
