# Generated by Django 3.1.3 on 2023-01-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('player', '0040_auto_20221217_1824'),
        ('factory', '0004_auto_20230115_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'factory'), ('model', 'Workplace')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
