# Generated by Django 3.1.3 on 2023-01-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('factory', '0005_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'factory'), ('model', 'Workshop')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
