# Generated by Django 3.1.3 on 2023-01-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_auto_20230115_2137'),
        ('factory', '0003_auto_20230116_1250'),
    ]

    operations = [
    ]
