# Generated by Django 3.1.3 on 2023-03-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_auto_20230329_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='good',
            field=models.CharField(choices=[('gas', 'Бензин'), ('diesel', 'Дизель'), ('plastic', 'Дизель'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Алюминий'), ('drilling', 'Алюминий'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('antitank', 'ПТ-орудия'), ('mines', 'Мины'), ('ifv', 'БМП'), ('drone', 'БПЛА')], default=None, max_length=20, verbose_name='Товар'),
        ),
    ]
