# Generated by Django 3.1.3 on 2023-05-29 21:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0051_auto_20230330_1048'),
        ('player', '0049_auto_20230426_2138'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('factory', '0012_auto_20230330_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('good', models.CharField(blank=True, choices=[('gas', 'Бензин'), ('diesel', 'Дизель'), ('plastic', 'Дизель'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Алюминий'), ('drilling', 'Алюминий'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('antitank', 'ПТ-орудия'), ('mines', 'Мины'), ('ifv', 'БМП'), ('drone', 'БПЛА')], max_length=10, null=True, verbose_name='Ресурс')),
                ('title', models.CharField(max_length=1, verbose_name='Номер схемы')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
                ('storage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='produce_storage', to='storage.storage', verbose_name='Склад')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Автоматическое производство',
                'verbose_name_plural': 'Автоматические производства',
            },
        ),
    ]
