# Generated by Django 3.1.3 on 2023-05-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_autoproduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoproduce',
            old_name='title',
            new_name='schema',
        ),
        migrations.AlterField(
            model_name='autoproduce',
            name='good',
            field=models.CharField(blank=True, choices=[('gas', 'Бензин'), ('diesel', 'Дизель'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('drilling', 'Буровые установки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('antitank', 'ПТ-орудия'), ('mines', 'Мины'), ('ifv', 'БМП'), ('drone', 'БПЛА')], max_length=10, null=True, verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='good',
            field=models.CharField(choices=[('gas', 'Бензин'), ('diesel', 'Дизель'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('drilling', 'Буровые установки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('antitank', 'ПТ-орудия'), ('mines', 'Мины'), ('ifv', 'БМП'), ('drone', 'БПЛА')], default=None, max_length=20, verbose_name='Товар'),
        ),
    ]
