# Generated by Django 3.1.3 on 2023-09-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0072_auto_20230903_1430'),
        ('factory', '0014_auto_20230601_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('energy_cost', models.IntegerField(default=1, verbose_name='Затраты энергии')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Чертёж',
                'verbose_name_plural': 'Чертежи',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.blueprint', verbose_name='Чертёж')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Сырьё')),
            ],
            options={
                'verbose_name': 'Чертёж',
                'verbose_name_plural': 'Чертежи',
            },
        ),
    ]
