# Generated by Django 3.1.3 on 2023-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_blueprint_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
