# Generated by Django 3.1.3 on 2023-09-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0017_blueprint_cash_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionlog',
            old_name='good',
            new_name='old_good',
        ),
    ]
