# Generated by Django 3.1.3 on 2023-09-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0072_auto_20230903_1430'),
        ('factory', '0018_auto_20230910_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='Наличные'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='good',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар'),
        ),
    ]
