# Generated by Django 3.1.3 on 2023-09-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0020_auto_20230910_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoproduce',
            old_name='good',
            new_name='old_good',
        ),
    ]
