# Generated by Django 3.1.3 on 2023-09-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0072_auto_20230903_1430'),
        ('factory', '0021_auto_20230910_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoproduce',
            name='good',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='autoproduce',
            name='old_good',
            field=models.CharField(blank=True, choices=[('gas', 'Бензин'), ('diesel', 'Дизель'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('drilling', 'Буровые установки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('antitank', 'ПТ-орудия'), ('mines', 'Мины'), ('ifv', 'БМП'), ('drone', 'БПЛА')], default=None, max_length=10, null=True, verbose_name='не используется'),
        ),
    ]
