# Generated by Django 3.1.3 on 2023-10-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_auto_20230911_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoproduce',
            name='schema',
            field=models.IntegerField(default=1, verbose_name='Номер схемы'),
        ),
    ]
