# Generated by Django 3.1.3 on 2022-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20220313_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='building',
            field=models.CharField(blank=True, choices=[('Hospital', 'Больница')], default=None, max_length=20, null=True, verbose_name='Здание'),
        ),
    ]
