# Generated by Django 3.1.3 on 2022-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20220404_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='building',
            field=models.CharField(blank=True, choices=[('Hospital', 'Больница'), ('PowerPlant', 'ТЭЦ')], default=None, max_length=20, null=True, verbose_name='Здание'),
        ),
    ]
