# Generated by Django 3.1.3 on 2022-04-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20220407_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='building',
            field=models.CharField(blank=True, choices=[('PowerPlant', 'ТЭЦ'), ('Hospital', 'Больница')], default=None, max_length=20, null=True, verbose_name='Здание'),
        ),
    ]
