# Generated by Django 3.1.3 on 2022-10-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_auto_20220828_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='building',
            field=models.CharField(blank=True, choices=[('PowerPlant', 'ТЭЦ'), ('Hospital', 'Больница'), ('Defences', 'Укрепления')], default=None, max_length=20, null=True, verbose_name='Здание'),
        ),
    ]
