# Generated by Django 3.1.3 on 2022-12-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_startwar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startwar',
            options={'verbose_name': 'Объявление войны', 'verbose_name_plural': 'Объявления войн'},
        ),
    ]
