# Generated by Django 3.1.3 on 2022-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_auto_20221227_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startwar',
            name='war_type',
            field=models.CharField(blank=True, choices=[], default='GroundWar', max_length=10, null=True, verbose_name='Тип войны'),
        ),
    ]
