# Generated by Django 3.1.3 on 2023-01-19 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0056_auto_20230120_0044'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('region', '0027_auto_20230119_2031'),
        ('player', '0041_auto_20230116_1250'),
        ('bill', '0020_auto_20230120_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeologicalSurveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Рассматривается')),
                ('type', models.CharField(blank=True, choices=[('ac', 'Принят'), ('rj', 'Отклонён'), ('cn', 'Отменён')], default=None, max_length=2, null=True, verbose_name='Решение')),
                ('cash_cost', models.BigIntegerField(default=0, verbose_name='Наличные')),
                ('voting_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Время начала рассмотрения')),
                ('voting_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True, verbose_name='Время завершения рассмотрения')),
                ('resource', models.CharField(blank=True, choices=[('gold', 'Золото'), ('oil', 'Нефть'), ('ore', 'Руда')], default=None, max_length=4, null=True, verbose_name='Ресурс')),
                ('exp_value', models.IntegerField(default=0, verbose_name='Объем разведки')),
                ('drilling_cost', models.BigIntegerField(default=0, verbose_name='Наличные')),
                ('initiator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player', verbose_name='Инициатор')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliament', verbose_name='Закон в парламенте')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион разведки')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask')),
                ('votes_con', models.ManyToManyField(blank=True, related_name='geologicalsurveys_votes_con', to='player.Player', verbose_name='Голоса "против"')),
                ('votes_pro', models.ManyToManyField(blank=True, related_name='geologicalsurveys_votes_pro', to='player.Player', verbose_name='Голоса "за"')),
            ],
            options={
                'verbose_name': 'Геологические изыскания',
                'verbose_name_plural': 'Геологические изыскания',
            },
        ),
    ]
