# Generated by Django 3.1.3 on 2023-02-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0022_independence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='independence',
            options={'verbose_name': 'Объявление независимости', 'verbose_name_plural': 'Объявления независимости'},
        ),
    ]
