# Generated by Django 3.1.3 on 2023-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0023_auto_20230206_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeresidency',
            name='drone_cost',
            field=models.IntegerField(default=1, verbose_name='Стоимость - дроны'),
        ),
        migrations.AddField(
            model_name='changeresidency',
            name='rifle_cost',
            field=models.IntegerField(default=1, verbose_name='Стоимость - автоматы'),
        ),
    ]
