# Generated by Django 3.1.3 on 2023-09-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0025_auto_20230329_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeologicalSurveys',
        ),
    ]
