# Generated by Django 3.1.3 on 2023-09-09 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0072_auto_20230903_1430'),
        ('bill', '0027_auto_20230909_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseauction',
            name='good',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Закупаемый товар'),
        ),
    ]
