# Generated by Django 3.1.3 on 2023-09-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0028_purchaseauction_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startwar',
            name='war_type',
            field=models.CharField(blank=True, choices=[], default=None, max_length=20, null=True, verbose_name='Тип войны'),
        ),
    ]
