# Generated by Django 3.1.3 on 2023-09-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0029_auto_20230911_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartWar',
        ),
    ]
