# Generated by Django 3.1.3 on 2023-10-28 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0030_delete_startwar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetaxes',
            name='new_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Новый налог'),
        ),
    ]
