# Generated by Django 3.1.3 on 2023-12-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0032_startwar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeResidency',
        ),
    ]
