# Generated by Django 3.1.3 on 2024-03-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0034_changeresidency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='building',
            field=models.CharField(blank=True, choices=[('PowerPlant', 'ТЭЦ'), ('Hospital', 'Больница'), ('Defences', 'Укрепления'), ('Infrastructure', 'Инфраструктура')], default=None, max_length=20, null=True, verbose_name='Здание'),
        ),
    ]
