# Generated by Django 3.1.3 on 2024-04-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0067_parliament_foundation_date'),
        ('bill', '0037_auto_20240420_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferaccept',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='state.state', verbose_name='Отдаёт'),
        ),
        migrations.AlterField(
            model_name='transferregion',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catcher', to='state.state', verbose_name='Принимает'),
        ),
    ]
