# Generated by Django 3.2.18 on 2024-08-25 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0086_alter_skilltraining_skill'),
        ('region', '0057_auto_20240619_2348'),
        ('state', '0067_parliament_foundation_date'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('bill', '0038_auto_20240427_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='MartialLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Рассматривается')),
                ('type', models.CharField(blank=True, choices=[('ac', 'Принят'), ('rj', 'Отклонён'), ('cn', 'Отменён')], default=None, max_length=2, null=True, verbose_name='Решение')),
                ('cash_cost', models.BigIntegerField(default=0, verbose_name='Наличные')),
                ('voting_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Время начала рассмотрения')),
                ('voting_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True, verbose_name='Время завершения рассмотрения')),
                ('active', models.BooleanField(default=False, verbose_name='Активно')),
                ('days_left', models.IntegerField(default=0, verbose_name='Прошло дней')),
                ('active_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True, verbose_name='Время завершения ВП')),
                ('initiator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player', verbose_name='Инициатор')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliament', verbose_name='Закон в парламенте')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион объявления')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask')),
                ('votes_con', models.ManyToManyField(blank=True, related_name='martiallaw_votes_con', to='player.Player', verbose_name='Голоса "против"')),
                ('votes_pro', models.ManyToManyField(blank=True, related_name='martiallaw_votes_pro', to='player.Player', verbose_name='Голоса "за"')),
            ],
            options={
                'verbose_name': 'Военное положение',
                'verbose_name_plural': 'Военные положения',
            },
        ),
    ]
