# Generated by Django 3.2.18 on 2024-08-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0039_martiallaw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='martiallaw',
            name='active',
        ),
        migrations.RemoveField(
            model_name='martiallaw',
            name='active_end',
        ),
        migrations.RemoveField(
            model_name='martiallaw',
            name='days_left',
        ),
    ]
