# Generated by Django 3.2.18 on 2024-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0040_auto_20240825_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='martiallaw',
            name='mode',
            field=models.CharField(choices=[('free', 'Снятие ограничений'), ('set', 'Военное положение')], default='free', max_length=4),
        ),
    ]
