# Generated by Django 3.2.18 on 2024-09-06 19:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0087_auto_20240619_2143'),
        ('state', '0067_parliament_foundation_date'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('player', '0087_auto_20240831_2244'),
        ('bill', '0041_martiallaw_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Рассматривается')),
                ('type', models.CharField(blank=True, choices=[('ac', 'Принят'), ('rj', 'Отклонён'), ('cn', 'Отменён')], default=None, max_length=2, null=True, verbose_name='Решение')),
                ('cash_cost', models.BigIntegerField(default=0, verbose_name='Наличные')),
                ('voting_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Время начала рассмотрения')),
                ('voting_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True, verbose_name='Время завершения рассмотрения')),
                ('send_cash', models.BooleanField(default=False, verbose_name='Отправка наличных')),
                ('send_count', models.BigIntegerField(default=0, verbose_name='Количество')),
                ('initiator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player', verbose_name='Инициатор')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliament', verbose_name='Закон в парламенте')),
                ('send_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар')),
                ('send_treasury', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='send_treasury', to='state.treasury', verbose_name='Казна списания')),
                ('take_treasury', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='take_treasury', to='state.treasury', verbose_name='Казна начисления')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask')),
                ('votes_con', models.ManyToManyField(blank=True, related_name='transferresources_votes_con', to='player.Player', verbose_name='Голоса "против"')),
                ('votes_pro', models.ManyToManyField(blank=True, related_name='transferresources_votes_pro', to='player.Player', verbose_name='Голоса "за"')),
            ],
            options={
                'verbose_name': 'Передача региона',
                'verbose_name_plural': 'Передачи регионов',
            },
        ),
    ]
