# Generated by Django 3.2.18 on 2024-09-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0042_transferresources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferresources',
            options={'verbose_name': 'Передача ресурсов', 'verbose_name_plural': 'Передачи ресурсов'},
        ),
    ]
