# Generated by Django 3.2.18 on 2024-10-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0043_alter_transferresources_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferresources',
            options={'verbose_name': 'Передача товаров', 'verbose_name_plural': 'Передачи товаров'},
        ),
    ]
