# Generated by Django 3.2.18 on 2024-12-16 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0111_alter_goldlog_activity_txt'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('state', '0068_state_message'),
        ('bill', '0044_alter_transferresources_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Рассматривается')),
                ('type', models.CharField(blank=True, choices=[('ac', 'Принят'), ('rj', 'Отклонён'), ('cn', 'Отменён')], default=None, max_length=2, null=True, verbose_name='Решение')),
                ('cash_cost', models.BigIntegerField(default=0, verbose_name='Наличные')),
                ('voting_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Время начала рассмотрения')),
                ('voting_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True, verbose_name='Время завершения рассмотрения')),
                ('resource', models.CharField(blank=True, choices=[('gold', 'Золото'), ('oil', 'Нефть'), ('ore', 'Руда')], default=None, max_length=4, null=True, verbose_name='Ресурс')),
                ('exp_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Общий объем разведки')),
                ('initiator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player', verbose_name='Инициатор')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliament', verbose_name='Закон в парламенте')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask')),
                ('votes_con', models.ManyToManyField(blank=True, related_name='exploreall_votes_con', to='player.Player', verbose_name='Голоса "против"')),
                ('votes_pro', models.ManyToManyField(blank=True, related_name='exploreall_votes_pro', to='player.Player', verbose_name='Голоса "за"')),
            ],
            options={
                'verbose_name': 'Разведка всех регионов',
                'verbose_name_plural': 'Разведки всех регионов',
            },
        ),
    ]
