# Generated by Django 3.2.18 on 2024-12-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0066_spawn'),
        ('bill', '0045_exploreall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreAllRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Общий объем разведки')),
                ('exp_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.exploreall', verbose_name='Законопроект')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион разведки')),
            ],
            options={
                'verbose_name': 'Часть общей разведки',
                'verbose_name_plural': 'Части общей разведки',
            },
        ),
    ]
