# Generated by Django 3.1.3 on 2020-12-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('based', models.BooleanField(default=False, verbose_name='Неудаляемая должность')),
                ('party_lead', models.BooleanField(default=False, verbose_name='Лидер партии')),
                ('party_sec', models.BooleanField(default=False, verbose_name='Секретарь партии')),
                ('party', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pos_of_party', to='party.party', verbose_name='Партия-Автор')),
            ],
            options={
                'verbose_name': 'Пост в партии',
                'verbose_name_plural': 'Посты в партиях',
            },
        ),
    ]
