# Generated by Django 3.1.3 on 2020-12-19 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_partyposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Идут прямо сейчас')),
                ('prim_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('prim_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Праймериз в партии')),
            ],
            options={
                'verbose_name': 'Праймериз в партии',
                'verbose_name_plural': 'Праймериз',
            },
        ),
    ]
