# Generated by Django 3.1.3 on 2020-12-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20201213_1838'),
        ('party', '0003_primaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimBulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='player.player', verbose_name='Кандидат')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='player.player', verbose_name='Голосовавший')),
                ('primaries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.primaries', verbose_name='Праймериз')),
            ],
            options={
                'verbose_name': 'Голос на праймериз',
                'verbose_name_plural': 'Голоса на праймериз',
            },
        ),
        migrations.CreateModel(
            name='PrimariesLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Лидер праймериз')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Лидер в партии')),
            ],
            options={
                'verbose_name': 'Лидер праймериз',
                'verbose_name_plural': 'Лидеры праймериз',
            },
        ),
    ]
