# Generated by Django 3.1.3 on 2020-12-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20201213_1838'),
        ('party', '0004_primariesleader_primbulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Партия вступления')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Заявка в партию',
                'verbose_name_plural': 'Заявки в партии',
            },
        ),
    ]
