# Generated by Django 3.1.3 on 2020-12-19 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20201213_1838'),
        ('party', '0005_partyapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Время создания записи')),
                ('exit_dtime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время выхода из партии')),
                ('party', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='member_of_party', to='party.party', verbose_name='Партия-Автор')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Лог партийной активности',
                'verbose_name_plural': 'Логи партийной активности',
            },
        ),
    ]
