# Generated by Django 3.1.3 on 2021-01-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_membershiplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyapply',
            name='status',
            field=models.CharField(choices=[('op', 'Новая заявка'), ('cs', 'Отозванная заявка'), ('cs', 'Одобренная заявка'), ('ac', 'Одобренная заявка'), ('rj', 'Отклонённая заявка'), ('ra', 'Отклонена с другими')], default='op', max_length=2),
        ),
    ]
