# Generated by Django 3.1.3 on 2021-01-04 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_auto_20210104_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyapply',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 20, 26, 7, 210171, tzinfo=utc)),
        ),
    ]
