# Generated by Django 3.1.3 on 2021-01-04 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0009_partyapply_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyapply',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
