# Generated by Django 3.1.3 on 2021-01-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_auto_20210104_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='members_image_link',
        ),
        migrations.AddField(
            model_name='party',
            name='members_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/party_backs/', verbose_name='Ссылка партийный фон'),
        ),
    ]
