# Generated by Django 3.1.3 on 2021-01-10 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20201213_1838'),
        ('party', '0011_auto_20210104_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyapply',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='partyapply',
            name='dtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи'),
        ),
        migrations.AlterField(
            model_name='membershiplog',
            name='dtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи'),
        ),
        migrations.AlterField(
            model_name='partyapply',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж'),
        ),
    ]
