# Generated by Django 3.1.3 on 2021-04-03 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0013_party_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaries',
            name='prim_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='primaries',
            name='prim_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True),
        ),
    ]
