# Generated by Django 3.1.3 on 2021-04-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('party', '0014_auto_20210409_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask'),
        ),
    ]
