# Generated by Django 3.1.3 on 2021-06-25 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0015_auto_20210417_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaries',
            name='prim_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 25, 17, 16, 50, 484117, tzinfo=utc), null=True),
        ),
    ]
