# Generated by Django 3.1.3 on 2021-06-25 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0016_auto_20210625_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaries',
            name='prim_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='primaries',
            name='prim_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 25, 18, 18, 40, 470374, tzinfo=utc), null=True),
        ),
    ]
