# Generated by Django 3.1.3 on 2021-07-19 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0017_auto_20210625_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaries',
            name='prim_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
