# Generated by Django 3.1.3 on 2022-10-21 21:07

from django.db import migrations
from django.utils import timezone
import json

def crontask_remake(apps, schema_editor):

    Party = apps.get_model("party", "Party")
    Primaries = apps.get_model("party", "Primaries")
    
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    
    
    parties = Party.objects.filter(deleted=False)
    
    for party in parties:
    
        Primaries.objects.filter(party=party).delete()
    
        if party.task is not None:
            task_identificator = party.task.id
            
            Party.objects.select_related('task').filter(pk=party.id).update(task=None)
            
            PeriodicTask.objects.filter(pk=task_identificator).delete()
        
        foundation_day = party.foundation_date.weekday()

        if foundation_day == 6:
            cron_day = 0
        else:
            cron_day = foundation_day + 1
        
        schedule, created = CrontabSchedule.objects.get_or_create(
                                                            minute=str(party.foundation_date.minute),
                                                            hour=str(party.foundation_date.hour),
                                                            day_of_week=cron_day,
                                                            day_of_month='*',
                                                            month_of_year='*',
                                                           )
                                                           
        task = PeriodicTask(
            name=party.title + ', id ' + str(party.pk),
            task='start_primaries',
            crontab=schedule,
            args=json.dumps([party.id]),
            start_time=timezone.now()
        )
        task.save()
        
        party.task = task
        
        party.save()
        


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0022_auto_20221011_1613'),
    ]

    operations = [
        migrations.RunPython(crontask_remake),
    ]
