# Generated by Django 3.1.3 on 2022-11-04 14:09

from django.db import migrations
from django.utils import timezone
import json

def crontask_remake(apps, schema_editor):

    Party = apps.get_model("party", "Party")
    Primaries = apps.get_model("party", "Primaries")
    
    parties = Party.objects.filter(deleted=False)
    
    for party in parties:
    
        if party.task is not None:
            
            party.task.name = 'Начало праймериз, id ' + str(party.pk)
            party.task.save()
            
        if Primaries.objects.filter(party=party, task__isnull=False).exists():
        
            primaries = Primaries.objects.get(party=party, task__isnull=False)
            primaries.task.name = 'Конец праймериз, id ' + str(party.pk)
            primaries.task.save()            
            


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0030_auto_20221102_1527'),
    ]

    operations = [
         migrations.RunPython(crontask_remake),
    ]
