# Generated by Django 3.1.3 on 2023-11-09 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0032_party_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='primaries_day',
            field=models.IntegerField(default=0, verbose_name='День праймериз'),
        ),
        migrations.AddField(
            model_name='party',
            name='primaries_time',
            field=models.TimeField(default=datetime.time(18, 9, 54, 213254), verbose_name='Время праймериз'),
        ),
    ]
