# Generated by Django 3.1.3 on 2023-11-10 06:40

from django.db import migrations, models


def set_weekday(apps, schema_editor):

    Party = apps.get_model("party", "Party")
    
    parties = Party.objects.all()
    
    for party in parties:
    
        party.primaries_day = party.foundation_date.weekday()
    
        party.save()       
            

class Migration(migrations.Migration):

    dependencies = [
        ('party', '0034_auto_20231110_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='primaries_day',
            field=models.IntegerField(default=0, verbose_name='День праймериз'),
        ),
        
        migrations.RunPython(set_weekday),
    ]
