# Generated by Django 3.1.3 on 2023-11-11 12:42

from django.db import migrations


def clear_tasks(apps, schema_editor):

    Party = apps.get_model("party", "Party")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    
    parties = Party.objects.all()
    
    for party in parties:
    
        if party.task:
        
            task_id = party.task.pk
            party.task = None
            party.save()

            PeriodicTask.objects.filter(pk=task_id).delete()
        
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('party', '0035_party_primaries_day'),
    ]

    operations = [
        migrations.RunPython(clear_tasks),
    ]
