# Generated by Django 3.1.3 on 2023-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0037_auto_20231111_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='gold',
            field=models.BigIntegerField(default=0, verbose_name='Золото'),
        ),
    ]
