# Generated by Django 3.2.18 on 2024-11-30 01:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0038_party_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyGoldLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('gold', models.BigIntegerField(default=0, verbose_name='Золота передано')),
                ('activity_txt', models.CharField(blank=True, choices=[('rating', 'Места в рейтинге'), ('parl_zp', 'Зарплата парламентским'), ('salary', 'Выдача золота')], max_length=10, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Лог партийного золота',
                'verbose_name_plural': 'Логи партийного золота',
            },
        ),
    ]
