# Generated by Django 3.1.3 on 2020-11-28 09:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='state.region', verbose_name='Регион проживания'),
        ),
        migrations.AddField(
            model_name='player',
            name='residency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residency', to='state.region', verbose_name='Прописка'),
        ),
        migrations.AlterField(
            model_name='player',
            name='account',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
        ),
        migrations.AlterField(
            model_name='player',
            name='energy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Энергии сейчас'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='player',
            name='residency_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата получния прописки'),
        ),
    ]
