# Generated by Django 3.1.3 on 2020-12-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_partyposition'),
        ('player', '0002_auto_20201202_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='party',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to='party.party', verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='player',
            name='party_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_post', to='party.partyposition', verbose_name='Должность в партии'),
        ),
    ]
