# Generated by Django 3.1.3 on 2021-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20210319_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chat_ban',
            field=models.BooleanField(default=False, verbose_name='Бан чата'),
        ),
    ]
