# Generated by Django 3.1.3 on 2021-03-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('player', '0004_cashlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('mine', 'Майнинг'), ('store', 'Операции со Складом'), ('trans', 'Передача товаров'), ('trade', 'Торговля')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
