# Generated by Django 3.1.3 on 2021-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_player_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_top',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рейтинг госпиталя при последнем приросте'),
        ),
        migrations.AddField(
            model_name='player',
            name='natural_refill',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время прироста'),
        ),
    ]
