# Generated by Django 3.1.3 on 2021-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20210312_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlog',
            name='cash',
            field=models.BigIntegerField(default=0, verbose_name='Денег передано'),
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
