# Generated by Django 3.1.3 on 2021-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20210312_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
