# Generated by Django 3.1.3 on 2021-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20211010_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(default='', max_length=250, null=True, verbose_name='Биография'),
        ),
    ]
