# Generated by Django 3.1.3 on 2021-10-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_player_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Биография'),
        ),
    ]
