# Generated by Django 3.1.3 on 2021-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_player_energy_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='paid_consumption',
            field=models.IntegerField(default=0, verbose_name='Оплаченный расход энергии'),
        ),
        migrations.AddField(
            model_name='player',
            name='paid_sum',
            field=models.IntegerField(default=0, verbose_name='Оплачено сегодня'),
        ),
    ]
