# Generated by Django 3.1.3 on 2022-01-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20211126_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('daily', 'Финансирование'), ('mine', 'Майнинг'), ('flyin', 'Перелёт'), ('n_str', 'Новый Склад'), ('store', 'Операции со Складом'), ('trans', 'Передача товаров'), ('trade', 'Торговля'), ('auct', 'Гос. закупки')], max_length=5, null=True),
        ),
    ]
