# Generated by Django 3.1.3 on 2022-02-20 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('player', '0012_auto_20220116_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('gold', models.BigIntegerField(default=0, verbose_name='Денег передано')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('activity_txt', models.CharField(blank=True, choices=[('reward', 'Бонус за репост'), ('mine', 'Майнинг'), ('nick', 'Смена никнейма'), ('avatar', 'Смена аватара'), ('stick', 'Покупка стикеров'), ('energy', 'Энергетики'), ('party', 'Новая партия')], max_length=6, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Лог золота',
                'verbose_name_plural': 'Логи золота',
            },
        ),
    ]
