# Generated by Django 3.1.3 on 2022-04-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_auto_20220418_0053'),
        ('player', '0016_automining'),
    ]

    operations = [
    ]
