# Generated by Django 3.1.3 on 2022-04-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_automining_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('reward', 'Бонус за репост'), ('mine', 'Майнинг'), ('aumine', 'Авто-майнинг'), ('nick', 'Смена никнейма'), ('avatar', 'Смена аватара'), ('stick', 'Покупка стикеров'), ('energy', 'Энергетики'), ('party', 'Новая партия')], max_length=6, null=True),
        ),
    ]
