# Generated by Django 3.1.3 on 2022-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0019_auto_20220421_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cards_count',
            field=models.IntegerField(default=0, verbose_name='Премиум-карты'),
        ),
    ]
