# Generated by Django 3.1.3 on 2022-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0026_auto_20220903_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersettings',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'Deutsch')], default=None, max_length=7, null=True, verbose_name='Язык в игре'),
        ),
    ]
