# Generated by Django 3.1.3 on 2022-10-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0027_playersettings_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersettings',
            name='party_back',
            field=models.BooleanField(default=True, verbose_name='Партийный фон'),
        ),
    ]
