# Generated by Django 3.1.3 on 2022-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0029_player_daily_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersettings',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'Deutsch'), ('be', 'Belarusian')], default=None, max_length=7, null=True, verbose_name='Язык в игре'),
        ),
    ]
