# Generated by Django 3.1.3 on 2022-10-23 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0030_auto_20221018_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Включен')),
                ('title', models.CharField(max_length=30, verbose_name='Никнейм')),
                ('event_start', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 23, 20, 23, 35, 123464, tzinfo=utc), verbose_name='Время начала')),
                ('event_end', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 20, 23, 35, 123483, tzinfo=utc), null=True, verbose_name='Время завершения')),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
            },
        ),
        migrations.CreateModel(
            name='EventPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Очков события')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.gameevent', verbose_name='Рамка')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Участник ивента',
                'verbose_name_plural': 'Участники ивента',
            },
        ),
    ]
