# Generated by Django 3.1.3 on 2022-10-23 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0031_eventpart_gameevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpart',
            name='paid_points',
            field=models.IntegerField(default=0, verbose_name='Последний оплаченный этап'),
        ),
        migrations.AlterField(
            model_name='eventpart',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.gameevent', verbose_name='Ивент'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 21, 19, 32, 356531, tzinfo=utc), null=True, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 23, 21, 19, 32, 356515, tzinfo=utc), verbose_name='Время начала'),
        ),
    ]
