# Generated by Django 3.1.3 on 2022-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0032_auto_20221024_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='event_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время начала'),
        ),
    ]
