# Generated by Django 3.1.3 on 2022-11-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0033_auto_20221103_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='IP пользователя'),
        ),
    ]
