# Generated by Django 3.1.3 on 2022-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0036_auto_20221112_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerregionalexpense',
            options={'verbose_name': 'Траты энергии игрока', 'verbose_name_plural': 'Траты энерии игроков'},
        ),
        migrations.AddField(
            model_name='playersettings',
            name='full_auto',
            field=models.BooleanField(default=False, verbose_name='Энергетики в авто'),
        ),
    ]
