# Generated by Django 3.1.3 on 2022-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0037_auto_20221114_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersettings',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'Deutsch'), ('be', 'Belarusian'), ('tr', 'Turkish'), ('sr', 'Serbian'), ('id', 'Indonesian'), ('pt-br', 'Portuguese (Brazil)')], default=None, max_length=7, null=True, verbose_name='Язык в игре'),
        ),
    ]
