# Generated by Django 3.1.3 on 2022-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0038_auto_20221204_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='type',
            field=models.CharField(choices=[('hl', 'Хэллоуин'), ('ny', 'Новый год')], default='hl', max_length=2, verbose_name='Праздник'),
        ),
        migrations.AlterField(
            model_name='playersettings',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'Deutsch'), ('be', 'Belarusian'), ('es', 'Spanish'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('pt-br', 'Portuguese (Brazil)')], default=None, max_length=7, null=True, verbose_name='Язык в игре'),
        ),
    ]
