# Generated by Django 3.1.3 on 2023-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0040_auto_20221217_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltraining',
            name='skill',
            field=models.CharField(blank=True, choices=[('power', 'Сила'), ('knowledge', 'Знания'), ('endurance', 'Выносливость'), ('Excavation', 'Промышленная экскавация'), ('Standardization', 'Стандартизация')], max_length=20, null=True, verbose_name='Навык'),
        ),
    ]
