# Generated by Django 3.1.3 on 2023-01-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0041_auto_20230116_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='reason',
            field=models.TextField(blank=True, default='', max_length=25, null=True, verbose_name='Причина'),
        ),
    ]
