# Generated by Django 3.1.3 on 2023-01-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0042_player_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersettings',
            name='wiki_hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть кнопку Wiki'),
        ),
    ]
