# Generated by Django 3.1.3 on 2023-02-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0044_auto_20230202_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySpent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Энергии потрачено')),
                ('fin', models.BooleanField(default=False, verbose_name='Награда выдана')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Очки события',
                'verbose_name_plural': 'Очки мини-событий',
            },
        ),
    ]
