# Generated by Django 3.1.3 on 2023-03-14 11:46

from django.db import migrations, models
from django.utils import timezone
import datetime
import json

def recount_skills(apps, schema_editor):
    Player = apps.get_model("player", "Player")
    SkillTraining = apps.get_model("player", "SkillTraining")

    skills_list = ['power', 'knowledge', 'endurance']

    for player in Player.objects.filter(banned=False):

        sub = 0

        for skill in skills_list:
            # считаем, сколько у нас изучается навыков с этим именем
            skill_cnt = SkillTraining.objects.filter(player=player, skill=skill).count()

            sum_skills = getattr(player, skill) + skill_cnt

            paid_before = 0
            paid_after = 0

            for i in range(sum_skills+1):
                if i == 0 or i == 1:
                    continue
                paid_before += i * 1000
                paid_after += (i ** 2) * 10

            # считаем сколько потрачено до патча
            sub += paid_before - paid_after

        player.cash += sub
        player.save()

class Migration(migrations.Migration):

    dependencies = [
        ('player', '0045_energyspent'),
    ]

    operations = [
        migrations.RunPython(recount_skills),
    ]
