# Generated by Django 3.1.3 on 2023-04-12 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0046_auto_20230314_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='energy',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Энергии сейчас'),
        ),
    ]
