# Generated by Django 3.1.3 on 2023-04-16 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0047_auto_20230412_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='natural_refill',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время прироста'),
        ),
    ]
