# Generated by Django 3.1.3 on 2023-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0048_auto_20230416_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_top',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Рейтинг госпиталя при последнем приросте'),
        ),
        migrations.AlterField(
            model_name='playersettings',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'Deutsch'), ('be', 'Belarusian'), ('es', 'Spanish'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('lv', 'Latvian'), ('pt-br', 'Portuguese (Brazil)')], default=None, max_length=7, null=True, verbose_name='Язык в игре'),
        ),
    ]
