# Generated by Django 3.1.3 on 2023-06-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0049_auto_20230426_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersettings',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'Deutsch'), ('be', 'Belarusian'), ('es', 'Spanish'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('lv', 'Latvian'), ('az', 'Azerbaijani'), ('pt-br', 'Portuguese (Brazil)')], default=None, max_length=7, null=True, verbose_name='Язык в игре'),
        ),
    ]
