# Generated by Django 3.1.3 on 2023-05-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    def remove_autos(apps, schema_editor):
        AutoMining = apps.get_model('player', 'AutoMining')

        AutoMining.objects.all().delete()

    dependencies = [
        ('player', '0049_auto_20230426_2138'),
    ]

    operations = [
        migrations.RunPython(remove_autos)
    ]
