# Generated by Django 3.1.3 on 2023-07-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0050_auto_20230625_2126'),
        ('player', '0050_auto_20230514_1738'),
    ]

    operations = [
    ]
