# Generated by Django 3.1.3 on 2023-10-19 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0051_merge_20230715_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('reward', 'Бонус за репост'), ('donut', 'VK Donut'), ('mine', 'Майнинг'), ('aumine', 'Авто-майнинг'), ('stckow', 'Процент за стикеры'), ('nick', 'Смена никнейма'), ('avatar', 'Смена аватара'), ('stick', 'Покупка стикеров'), ('energy', 'Энергетики'), ('party', 'Новая партия'), ('ivent', 'Ивент')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='DonutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Лог VK Donut',
                'verbose_name_plural': 'Логи VK Donut',
            },
        ),
    ]
