# Generated by Django 3.1.3 on 2023-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0052_auto_20231019_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='educated',
            field=models.BooleanField(default=False, verbose_name='Прошёл обучение'),
        ),
    ]
