# Generated by Django 3.1.3 on 2023-12-19 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0055_auto_20231219_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lootbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Число сундуков')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Лутбоксы',
                'verbose_name_plural': 'Лутбоксы',
            },
        ),
    ]
