# Generated by Django 3.1.3 on 2023-12-19 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0056_lootbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('reward', 'Бонус за репост'), ('donut', 'VK Donut'), ('mine', 'Майнинг'), ('aumine', 'Авто-майнинг'), ('stckow', 'Процент за стикеры'), ('bx_gld', 'Золото из лутбокса'), ('nick', 'Смена никнейма'), ('avatar', 'Смена аватара'), ('stick', 'Покупка стикеров'), ('energy', 'Энергетики'), ('party', 'Новая партия'), ('ivent', 'Ивент'), ('boxes', 'Покупка лутбокса'), ('edu_01', 'Награда за прокачку характеристики'), ('edu_02', 'Награда за добытое сырьё'), ('edu_03', 'Награда за то, что тяпнул'), ('edu_04', 'Награда за длинную лекцию о Складе'), ('edu_05', 'Награда за изучение карты')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='PremLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('days', models.BigIntegerField(default=0, verbose_name='Дней начислено')),
                ('activity_txt', models.CharField(blank=True, choices=[('buying', 'Покупка'), ('lootbox', 'Награда из лутбокса')], max_length=7, null=True)),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Лог премиума',
                'verbose_name_plural': 'Логи премиума',
            },
        ),
    ]
