# Generated by Django 3.1.3 on 2023-12-19 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0057_auto_20231219_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildpassLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('count', models.BigIntegerField(default=0, verbose_name='Дней начислено')),
                ('activity_txt', models.CharField(blank=True, choices=[('buying', 'Покупка'), ('lootbox', 'Награда из лутбокса')], max_length=7, null=True)),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Лог Wild Pass',
                'verbose_name_plural': 'Логи Wild Pass',
            },
        ),
    ]
