# Generated by Django 3.1.3 on 2023-12-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0058_wildpasslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildpasslog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('buying', 'Покупка за реал'), ('lootbox', 'Награда из лутбокса'), ('trading', 'Торговля в игре')], max_length=7, null=True),
        ),
    ]
