# Generated by Django 3.1.3 on 2023-12-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    def giveaway_boxes(apps, schema_editor):
        Lootbox = apps.get_model('player', 'Lootbox')
        Player = apps.get_model('player', 'Player')
        
        for player in Player.objects.filter(banned=False):
        
            if Lootbox.objects.filter(player=player).exists():
                lbox = Lootbox.objects.get(player=player)
            else:
                lbox = Lootbox(player=player)
                
            lbox.stock += 1
            lbox.save()
    
    dependencies = [
        ('player', '0059_auto_20231220_0131'),
    ]

    operations = [
        migrations.RunPython(giveaway_boxes),
    ]
