# Generated by Django 3.1.3 on 2024-01-30 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0060_auto_20231224_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersettings',
            name='captcha_ans',
            field=models.IntegerField(default=0, verbose_name='Captcha'),
        ),
        migrations.AddField(
            model_name='playersettings',
            name='captcha_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата прохождения Captcha'),
        ),
    ]
