# Generated by Django 3.1.3 on 2024-03-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0061_auto_20240130_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Никнейм')),
                ('reusable', models.BooleanField(default=False, verbose_name='Многоразовый')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата истечения кода')),
                ('premium', models.IntegerField(default=0, verbose_name='Дни премиума')),
                ('gold', models.IntegerField(default=0, verbose_name='Золото')),
                ('wild_pass', models.IntegerField(default=0, verbose_name='Wild Pass')),
                ('cash', models.IntegerField(default=0, verbose_name='Деньги')),
            ],
            options={
                'verbose_name': 'Бонус-код',
                'verbose_name_plural': 'Бонус-коды',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='articles_ban',
            field=models.BooleanField(default=False, verbose_name='Бан статей'),
        ),
    ]
