# Generated by Django 3.1.3 on 2024-03-03 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0062_auto_20240304_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscode',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Бонус-код'),
        ),
        migrations.AlterField(
            model_name='bonuscode',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата истечения кода'),
        ),
    ]
