# Generated by Django 3.1.3 on 2024-03-03 23:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0063_auto_20240304_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='player.bonuscode', verbose_name='Код')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Использование кодов',
                'verbose_name_plural': 'Использование кодов',
            },
        ),
    ]
