# Generated by Django 3.1.3 on 2024-03-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0064_codeusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('daily', 'Финансирование'), ('mine', 'Майнинг'), ('flyin', 'Перелёт'), ('n_str', 'Новый Склад'), ('store', 'Операции со Складом'), ('trans', 'Передача товаров'), ('trade', 'Торговля'), ('bonus', 'Бонус-код'), ('auct', 'Гос. закупки'), ('skill', 'Навыки')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='goldlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('reward', 'Бонус за репост'), ('donut', 'VK Donut'), ('mine', 'Майнинг'), ('aumine', 'Авто-майнинг'), ('stckow', 'Процент за стикеры'), ('bx_gld', 'Золото из лутбокса'), ('bonus', 'Бонус-код'), ('nick', 'Смена никнейма'), ('avatar', 'Смена аватара'), ('stick', 'Покупка стикеров'), ('energy', 'Энергетики'), ('party', 'Новая партия'), ('ivent', 'Ивент'), ('boxes', 'Покупка лутбокса'), ('edu_01', 'Награда за прокачку характеристики'), ('edu_02', 'Награда за добытое сырьё'), ('edu_03', 'Награда за то, что тяпнул'), ('edu_04', 'Награда за длинную лекцию о Складе'), ('edu_05', 'Награда за изучение карты')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='premlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('buying', 'Покупка'), ('bonus', 'Бонус-код'), ('lootbox', 'Награда из лутбокса')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='wildpasslog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('buying', 'Покупка за реал'), ('lootbox', 'Награда из лутбокса'), ('bonus', 'Бонус-код'), ('trading', 'Торговля в игре')], max_length=7, null=True),
        ),
    ]
