# Generated by Django 3.1.3 on 2024-04-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0065_auto_20240305_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltraining',
            name='skill',
            field=models.CharField(blank=True, choices=[('power', 'Сила'), ('knowledge', 'Знания'), ('endurance', 'Выносливость'), ('Excavation', 'Промышленная экскавация'), ('Fracturing', 'Гидроразрыв'), ('Standardization', 'Стандартизация')], max_length=20, null=True, verbose_name='Навык'),
        ),
    ]
