# Generated by Django 3.1.3 on 2024-05-05 22:03

from django.db import migrations
from datetime import datetime, timedelta
from django.utils import timezone

def add_codes(apps, schema_editor):

    bonus_codes = [
        '283-989-820',
        '884-545-186', 
        '612-141-810', 
        '978-471-747', 
        '296-470-192', 
        '577-224-181', 
        '105-956-631', 
        '476-393-530', 
        '939-316-725', 
        '674-385-963', 
        '088-166-199', 
        '121-605-844', 
        '762-570-291', 
        '671-756-525', 
        '637-897-622', 
        '847-769-896', 
        '984-133-103', 
        '796-975-587', 
        '868-943-449', 
        '803-631-727' 
    ]

    invite_codes = [
        '40-161-0991', 
        '79-335-9141', 
        '24-586-9395', 
        '18-014-8171', 
        '60-578-4557', 
        '20-052-5983', 
        '81-783-2178', 
        '27-770-4416', 
        '42-453-5439', 
        '21-373-2928', 
        '94-038-7057', 
        '41-890-6072', 
        '40-917-9858', 
        '80-793-7624', 
        '12-392-7469', 
        '53-187-9837', 
        '99-496-4934', 
        '40-297-7069', 
        '92-907-3336', 
        '57-347-7834'
    ]
    
    BonusCode = apps.get_model("player", "BonusCode")
    
    for text in bonus_codes:
        
        code = BonusCode(
                code=text,
                date=timezone.now() + timedelta(days=365),
                plane='nagger',
                color='dreamflight'
            )
        code.save()
    
    for text in invite_codes:
        
        code = BonusCode(
                code=text,
                invite=True,
                date=timezone.now() + timedelta(days=365),
                premium=14,
                gold=1000
            )
        code.save()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('player', '0068_auto_20240506_0050'),
    ]

    operations = [
        migrations.RunPython(add_codes),
    ]
