# Generated by Django 3.1.3 on 2024-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0072_auto_20240528_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscode',
            name='color',
            field=models.CharField(blank=True, choices=[('base', 'базовый'), ('red', 'красный'), ('orange', 'оранжевый'), ('yellow', 'желтый'), ('green', 'зелёный'), ('light_blue', 'голубой'), ('dark_blue', 'синий'), ('violet', 'фиолетовый'), ('pink', 'розовый'), ('black', 'чёрный'), ('gold', 'золотой'), ('dreamflight', 'Dreamflight'), ('black_gold', 'чёрно-золотой'), ('green_cam', 'зелёный камуфляж'), ('green_white_cam', 'бело-зелёный камуфляж'), ('blue_cam', 'синий камуфляж'), ('desert_cam', 'песочный камуфляж'), ('wood', 'дерево'), ('airball', 'Airball'), ('pobeda', 'пузырьки')], max_length=20, verbose_name='Цвет самолета'),
        ),
        migrations.AlterField(
            model_name='lootbox',
            name='garant_in',
            field=models.IntegerField(default=50, verbose_name='До гаранта'),
        ),
    ]
