# Generated by Django 3.1.3 on 2024-05-31 09:12

from django.db import migrations

def add_gold(apps, schema_editor):

    
    Player = apps.get_model("player", "Player")
    
    for player in Player.objects.filter():
        
        if player.image:
            player.gold += 250
            player.save()

class Migration(migrations.Migration):

    dependencies = [
        ('player', '0073_auto_20240530_0116'),
    ]

    operations = [
        migrations.RunPython(add_gold),
    ]
