# Generated by Django 3.1.3 on 2024-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0075_auto_20240601_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscode',
            name='plane',
            field=models.CharField(blank=True, choices=[('nagger', 'Nagger'), ('pretender', 'Pretender'), ('trickster', 'Trickster'), ('smuggler', 'Smuggler'), ('chaser', 'Chaser'), ('reaper', 'Reaper'), ('cheater', 'Cheater'), ('carrier', 'Carrier'), ('observer', 'Observer'), ('striker', 'Striker'), ('demolisher', 'Demolisher'), ('sprinter', 'Sprinter'), ('harrier', 'Harrier'), ('sailor', 'Sailor'), ('hammer', 'Hammer'), ('beluzzo', 'Диск Белуццо')], max_length=10, verbose_name='Самолёт'),
        ),
    ]
