# Generated by Django 3.1.3 on 2024-06-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0078_auto_20240602_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpart',
            name='boost',
            field=models.IntegerField(default=0, verbose_name='Бонус к дейлику'),
        ),
    ]
