# Generated by Django 3.1.3 on 2024-06-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0079_eventpart_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lootbox',
            name='garant_in',
            field=models.IntegerField(default=100, verbose_name='До гаранта'),
        ),
    ]
