# Generated by Django 3.2.18 on 2024-07-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0082_alter_player_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отпечаток браузера'),
        ),
    ]
