# Generated by Django 3.2.18 on 2024-07-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0082_auto_20240626_0022'),
        ('player', '0083_player_fingerprint'),
    ]

    operations = [
    ]
