# Generated by Django 3.2.18 on 2024-07-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0084_auto_20240715_2352'),
        ('player', '0084_merge_0082_auto_20240626_0022_0083_player_fingerprint'),
    ]

    operations = [
    ]
