# Generated by Django 3.2.18 on 2024-08-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0085_merge_20240716_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltraining',
            name='skill',
            field=models.CharField(blank=True, choices=[('power', 'Сила'), ('knowledge', 'Знания'), ('endurance', 'Выносливость'), ('Excavation', 'Промышленная экскавация'), ('Fracturing', 'Гидроразрыв'), ('Standardization', 'Стандартизация'), ('Biochemistry', 'Биохимия'), ('TrophyEngineering', 'Трофейная инженерия')], max_length=20, null=True, verbose_name='Навык'),
        ),
    ]
