# Generated by Django 3.2.18 on 2024-10-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0088_testlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество медалей')),
                ('type', models.CharField(choices=[('year', 'За год игры в WP')], default='year', max_length=10)),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Медаль',
                'verbose_name_plural': 'Медали',
            },
        ),
    ]
