# Generated by Django 3.2.18 on 2024-10-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0089_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='type',
            field=models.CharField(choices=[('year', 'За год игры в WP'), ('alpha', 'За альфа-тест WP'), ('beta', 'За бета-тест WP'), ('public', 'За открытый тест WP')], default='year', max_length=10),
        ),
    ]
