# Generated by Django 3.2.18 on 2024-10-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0092_auto_20241009_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpointusage',
            name='type',
            field=models.CharField(choices=[('7_prem', '7 дней према'), ('plane', 'Самолёт'), ('cash', 'Деньги'), ('gold', 'Золото'), ('wildpass', 'Wild Pass'), ('30_prem', '30 дней према')], default='7_prem', max_length=10),
        ),
    ]
