# Generated by Django 3.2.18 on 2024-10-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0094_alter_bonuscode_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpointusage',
            name='type',
            field=models.CharField(choices=[('7_prem', '7 дней према'), ('7_prem_2', '7 дней према (2)'), ('plane', 'Самолёт'), ('cash', 'Деньги'), ('gold', 'Золото'), ('gold_100_1', 'Золото 100'), ('gold_100_2', 'Золото 100 (2)'), ('wildpass', 'Wild Pass'), ('30_prem', '30 дней према')], default='7_prem', max_length=10),
        ),
    ]
