# Generated by Django 3.2.18 on 2024-10-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0095_alter_testpointusage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_33',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatars/33/', verbose_name='33px'),
        ),
        migrations.AddField(
            model_name='player',
            name='image_75',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatars/75/', verbose_name='75px'),
        ),
    ]
