# Generated by Django 3.2.18 on 2024-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0100_alter_playersettings_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('daily', 'Финансирование'), ('mine', 'Майнинг'), ('flyin', 'Перелёт'), ('n_str', 'Новый Склад'), ('store', 'Операции со Складом'), ('trans', 'Передача товаров'), ('trade', 'Торговля'), ('bonus', 'Бонус-код'), ('auct', 'Гос. закупки'), ('skill', 'Навыки'), ('financing', 'Награда за получение Финансирования')], max_length=10, null=True),
        ),
    ]
