# Generated by Django 3.2.18 on 2024-11-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0101_alter_cashlog_activity_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('daily', 'Финансирование'), ('mine', 'Майнинг'), ('flyin', 'Перелёт'), ('n_str', 'Новый Склад'), ('store', 'Операции со Складом'), ('trans', 'Передача товаров'), ('trade', 'Торговля'), ('bonus', 'Бонус-код'), ('auct', 'Гос. закупки'), ('skill', 'Навыки'), ('financing', 'Награда за получение Финансирования'), ('edu_skill', 'обучение: Изучение характеристики')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gold',
            field=models.BigIntegerField(default=1000, verbose_name='Золото'),
        ),
    ]
