# Generated by Django 3.2.18 on 2024-11-11 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0102_auto_20241111_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreebieUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи')),
                ('type', models.CharField(choices=[('cash_1m', 'Деньги 1млн')], default='7_prem', max_length=10)),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Получение бонуса',
                'verbose_name_plural': 'Получения бонуса',
            },
        ),
    ]
