# Generated by Django 3.2.18 on 2024-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0103_freebieusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freebieusage',
            name='type',
            field=models.CharField(choices=[('cash_500k', 'Деньги 500k')], default='7_prem', max_length=10),
        ),
    ]
