# Generated by Django 3.2.18 on 2024-11-16 23:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0105_alter_freebieusage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freebieusage',
            name='type',
            field=models.CharField(choices=[('gold_500', 'Золото 500'), ('cash_500k', 'Деньги 500k'), ('rate_gold', 'Золото за оценку')], default='7_prem', max_length=10),
        ),
        migrations.CreateModel(
            name='RateReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='Никнейм')),
                ('dtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время обновления записи')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Награды за оценку',
                'verbose_name_plural': 'Награды за оценку',
            },
        ),
    ]
