# Generated by Django 3.2.18 on 2024-11-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0107_alter_bonuscode_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='reason',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Причина'),
        ),
    ]
