# Generated by Django 3.2.18 on 2024-11-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0108_alter_player_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='type',
            field=models.CharField(choices=[('hl', 'Хэллоуин'), ('ny', 'Новый год'), ('su', 'Лето'), ('av', 'Годовщина'), ('fd', 'Чёрная пятница')], default='hl', max_length=2, verbose_name='Праздник'),
        ),
    ]
