# Generated by Django 3.2.18 on 2024-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0110_alter_goldlog_activity_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('reward', 'Бонус за репост'), ('donut', 'VK Donut'), ('mine', 'Майнинг'), ('aumine', 'Авто-майнинг'), ('stckow', 'Процент за авторство'), ('bx_gld', 'Золото из лутбокса'), ('bonus', 'Бонус-код'), ('partzp', 'Зарплата от партии'), ('leadzp', 'Зарплата лидера'), ('min_zp', 'Зарплата миинстра'), ('wpass', 'Активация Wildpass'), ('nick', 'Смена никнейма'), ('avatar', 'Смена аватара'), ('stick', 'Покупка стикеров'), ('energy', 'Энергетики'), ('party', 'Новая партия'), ('ivent', 'Ивент'), ('boxes', 'Покупка лутбокса'), ('rebel', 'Начало восстания'), ('edu_01', 'Награда за прокачку характеристики'), ('edu_02', 'Награда за добытое сырьё'), ('edu_03', 'Награда за то, что тяпнул'), ('edu_04', 'Награда за длинную лекцию о Складе'), ('edu_05', 'Награда за изучение карты')], max_length=6, null=True),
        ),
    ]
