# Generated by Django 3.2.18 on 2024-12-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0111_alter_goldlog_activity_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='количество')),
            ],
            options={
                'verbose_name': 'Джекпот',
                'verbose_name_plural': 'Джекпоты',
            },
        ),
        migrations.AlterField(
            model_name='cashlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('daily', 'Финансирование'), ('mine', 'Майнинг'), ('flyin', 'Перелёт'), ('n_str', 'Новый Склад'), ('store', 'Операции со Складом'), ('trans', 'Передача товаров'), ('trade', 'Торговля'), ('bonus', 'Бонус-код'), ('auct', 'Гос. закупки'), ('skill', 'Навыки'), ('box', 'Лутбокс'), ('financing', 'Награда за получение Финансирования'), ('edu_skill', 'обучение: Изучение характеристики')], max_length=10, null=True),
        ),
    ]
