# Generated by Django 3.2.18 on 2024-12-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0112_auto_20241224_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootbox',
            name='opened',
            field=models.IntegerField(default=0, verbose_name='Открыто сундуков'),
        ),
    ]
