# Generated by Django 3.2.18 on 2024-12-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0113_lootbox_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('daily', 'Финансирование'), ('mine', 'Майнинг'), ('flyin', 'Перелёт'), ('n_str', 'Новый Склад'), ('store', 'Операции со Складом'), ('trans', 'Передача товаров'), ('trade', 'Торговля'), ('bonus', 'Бонус-код'), ('auct', 'Гос. закупки'), ('skill', 'Навыки'), ('box', 'Лутбокс'), ('buy_box', 'Покупка лутбокса'), ('financing', 'Награда за получение Финансирования'), ('edu_skill', 'обучение: Изучение характеристики')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wildpasslog',
            name='activity_txt',
            field=models.CharField(blank=True, choices=[('buying', 'Покупка за реал'), ('lootbox', 'Награда из лутбокса'), ('box', 'Покупка лутбокса'), ('bonus', 'Бонус-код'), ('trading', 'Торговля в игре'), ('using', 'Активация')], max_length=7, null=True),
        ),
    ]
