# Generated by Django 3.2.18 on 2024-12-30 13:59

from django.db import migrations
from datetime import datetime, timedelta
from django.utils import timezone

def add_codes(apps, schema_editor):

    bonus_codes = [
        'W-1A3-B7X-Q9Z',  
        'W-C5D-F2H-J8L',  
        'W-M1N-P7Q-R6T',  
        'W-X3Y-Z4W-V2K',  
        'W-J9M-K8F-Q1D',  
        'W-A4T-B6X-C2P',  
        'W-L7H-P9M-J3Z',  
        'W-Q1K-R8N-V4D',  
        'W-X5C-B3T-J9F',  
        'W-P2L-M6Y-V8Q',
        'W-VVX-6TD-7KV-ADY',
        'W-E4F-I62-NF4-NDN',
        'W-X6M-K3S-PAI-5V8',
        'W-GVP-XAK-QS3-UDH',
        'W-0QP-R2X-YHM-V0V',
        'W-I8L-9RZ-R1I-SWS'
    ]

    
    BonusCode = apps.get_model("player", "BonusCode")
    
    for text in bonus_codes:
        
        code = BonusCode(
                code=text,
                date=timezone.now() + timedelta(days=365),
                wild_pass=1,
            )
        code.save()

class Migration(migrations.Migration):

    dependencies = [
        ('player', '0114_auto_20241225_0449'),
    ]

    operations = [
        migrations.RunPython(add_codes),
    ]
