# Generated by Django 3.2.18 on 2025-01-03 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0115_auto_20241230_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootbox',
            name='dtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи'),
        ),
    ]
