# Generated by Django 3.1.3 on 2022-02-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название набора')),
                ('creator', models.CharField(max_length=100, verbose_name='Автор набора')),
                ('creator_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на автора')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание набора')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Стикерпак',
                'verbose_name_plural': 'Стикерпаки',
            },
        ),
    ]
