# Generated by Django 3.1.3 on 2022-02-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_stickerpack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, verbose_name='Описание стикера')),
                ('image', models.ImageField(upload_to='img/stickers/', verbose_name='Стикер')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_pack', to='chat.stickerpack', verbose_name='Стикерпак')),
            ],
            options={
                'verbose_name': 'Стикер',
                'verbose_name_plural': 'Стикеры',
            },
        ),
    ]
