# Generated by Django 3.1.3 on 2022-02-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20220116_0249'),
        ('chat', '0003_sticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickersOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Игрок')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.stickerpack', verbose_name='Стикерпак')),
            ],
            options={
                'verbose_name': 'Владелец стикеров',
                'verbose_name_plural': 'Владельцы стикеров',
            },
        ),
    ]
