# Generated by Django 3.1.3 on 2022-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_stickersownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerpack',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
