# Generated by Django 3.1.3 on 2022-05-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0020_player_cards_count'),
        ('chat', '0005_stickerpack_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerpack',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_owner', to='player.player', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='percent',
            field=models.IntegerField(default=50, verbose_name='Процент с продажи'),
        ),
    ]
