# Generated by Django 3.1.3 on 2022-05-10 15:30

from django.db import migrations

def create_hospitals(apps, schema_editor):
    Player = apps.get_model("player", "Player")
    StickerPack = apps.get_model("chat", "StickerPack")
    StickersOwnership = apps.get_model("chat", "StickersOwnership")
    
    if Player.objects.filter(pk=67, nickname='Megumin').exists():
    
        player = Player.objects.get(pk=67)
        
        if StickerPack.objects.filter(title='Том').exists():
            StickerPack.objects.filter(title='Том').update(owner=player)
            
            gold = 0
        
            for pack in StickersOwnership.objects.filter(pack=StickerPack.objects.get(title='Том')):
                gold += 500
            
            player.gold += gold
            player.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20220510_1829'),
    ]

    operations = [
        migrations.RunPython(create_hospitals),
    ]
