# Generated by Django 3.1.3 on 2023-10-07 22:07

from django.db import migrations
import redis

def clear_chats(apps, schema_editor):
    Chat = apps.get_model("chat", "Chat")

    r = redis.StrictRedis(host='redis', port=6379, db=0)

    for chat in Chat.objects.all():
        # все сообщения в БД
        r.delete(f'dialogue_{chat.pk}')

    r.delete('chat_mess_dates')

    Chat.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20231002_0049'),
    ]

    operations = [
        migrations.RunPython(clear_chats),
    ]
