# Generated by Django 3.1.3 on 2023-10-07 22:48

from django.db import migrations
import redis

def clear_chats(apps, schema_editor):
    Player = apps.get_model("player", "Player")
    Chat = apps.get_model("chat", "Chat")

    r = redis.StrictRedis(host='redis', port=6379, db=0)

    players = Player.objects.all().values_list("pk")

    # ID игроков
    players_pk = []
    for player in players:
        players_pk.append(player[0])

    for player_pk in players_pk:
        # все сообщения в БД
        r.delete(f'chats_{player_pk}_unread')

    for chat in Chat.objects.all():
        # все сообщения в БД
        r.delete(f'dialogue_{chat.pk}')

    r.delete('chat_mess_dates')

    Chat.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20231008_0107'),
    ]

    operations = [
        migrations.RunPython(clear_chats),
    ]
