# Generated by Django 3.2.18 on 2024-10-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0068_state_message'),
        ('chat', '0012_chat_gov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='gov',
        ),
        migrations.AddField(
            model_name='chat',
            name='state',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_state', to='state.state', verbose_name='Государство'),
        ),
    ]
