# Generated by Django 3.2.18 on 2024-10-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0068_state_message'),
        ('chat', '0013_auto_20241015_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_state', to='state.state', verbose_name='Государство'),
        ),
    ]
