# Generated by Django 3.2.18 on 2024-10-24 21:14

from django.db import migrations
from PIL import Image
from PIL import features
from io import BytesIO
from django.core.files.base import ContentFile
import os
import re
    

def image_resize(apps, schema_editor):
    Sticker = apps.get_model('chat', 'Sticker')
    
    # лень переименовывать, но это СТИКЕРЫ а не Игроки
    for player in Sticker.objects.all():
        if player.image and os.path.isfile(player.image.path):
            # Открываем исходное изображение
            img = Image.open(player.image)
            img = img.resize((250, 250), Image.ANTIALIAS)

            img_io_75 = BytesIO()
            img.save(img_io_75, format='WEBP')
            tiny_image_75_name = re.split(r'[/.]', player.image.name)[-2] + '.webp'

            player.image.save(tiny_image_75_name, ContentFile(img_io_75.getvalue()), save=False)

            # Сохраняем изменения
            player.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20241024_1815'),
    ]

    operations = [
        migrations.RunPython(image_resize),
    ]
