# Generated by Django 3.2.18 on 2024-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20241025_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerpack',
            name='creator_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='creator_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='creator_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='description_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='description_it',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='description_sr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='title_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Название набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='title_sr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название набора'),
        ),
    ]
