# Generated by Django 3.2.18 on 2024-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20241028_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerpack',
            name='creator_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='description_hy',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание набора'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='title_hy',
            field=models.CharField(max_length=100, null=True, verbose_name='Название набора'),
        ),
    ]
