# Generated by Django 3.1.3 on 2024-02-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0061_auto_20240130_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=100, verbose_name='Статья')),
                ('body', models.TextField(verbose_name='Статья')),
                ('pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('pin_order', models.IntegerField(default=0, verbose_name='Приоритет закрепления')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
