# Generated by Django 3.2.18 on 2024-10-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20240305_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('messages', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
            options={
                'verbose_name': 'Блок комментариев',
                'verbose_name_plural': 'Блоки комментариев',
            },
        ),
    ]
