# Generated by Django 3.1.3 on 2024-02-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityeventpart',
            name='boost',
            field=models.IntegerField(default=0, verbose_name='Бонус к прокачке'),
        ),
    ]
