# Generated by Django 3.1.3 on 2024-03-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0065_auto_20240305_0121'),
        ('event', '0002_activityeventpart_boost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Включен')),
                ('title', models.CharField(max_length=30, verbose_name='Никнейм')),
                ('event_start', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время начала')),
                ('event_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время завершения')),
            ],
            options={
                'verbose_name': 'Ивент приглосов',
                'verbose_name_plural': 'Ивенты приглосов',
            },
        ),
        migrations.CreateModel(
            name='CashEventPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boost', models.IntegerField(default=0, verbose_name='Бонус к прокачке')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.cashevent', verbose_name='Ивент')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Участник ивента приглосов',
                'verbose_name_plural': 'Участники ивента приглосов',
            },
        ),
    ]
