# Generated by Django 3.1.3 on 2024-03-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20240323_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='сумма Характеристик'),
        ),
    ]
