# Generated by Django 3.1.3 on 2024-06-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_invite_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_event', to='event.cashevent', verbose_name='Событие'),
        ),
    ]
