# Generated by Django 3.1.3 on 2023-03-08 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('oil', models.BigIntegerField(default=0, verbose_name='Добыто нефти')),
                ('type', models.CharField(choices=[('wti_oil', 'WTI'), ('brent_oil', 'Brent'), ('urals_oil', 'Urals')], default='urals_oil', max_length=10)),
            ],
            options={
                'verbose_name': 'Нефти за день',
                'verbose_name_plural': 'Нефти за день',
            },
        ),
    ]
