# Generated by Django 3.1.3 on 2023-03-08 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_dailyoil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ore', models.BigIntegerField(default=0, verbose_name='Добыто руды')),
                ('type', models.CharField(choices=[('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы')], default='coal', max_length=7)),
            ],
            options={
                'verbose_name': 'Руд за день',
                'verbose_name_plural': 'Руд за день',
            },
        ),
    ]
