# Generated by Django 3.2.18 on 2024-10-22 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_dailyore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('gold', models.BigIntegerField(default=0, verbose_name='Добыто золота')),
            ],
            options={
                'verbose_name': 'Золота за день',
                'verbose_name_plural': 'Золота за день',
            },
        ),
    ]
