# Generated by Django 3.2.18 on 2024-11-18 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0068_state_message'),
        ('metrics', '0004_dailygold'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoldByState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('gold', models.BigIntegerField(default=0, verbose_name='Добыто золота')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dailygoldbystate_state', to='state.state', verbose_name='Государство')),
            ],
            options={
                'verbose_name': 'Золота за день в государства',
                'verbose_name_plural': 'Золота за день в государства',
            },
        ),
    ]
