# Generated by Django 3.2.18 on 2024-11-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_dailygoldbystate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailygoldbystate',
            options={'verbose_name': 'Золота за день в государстве', 'verbose_name_plural': 'Золота за день в государствах'},
        ),
    ]
