# Generated by Django 3.2.18 on 2024-11-23 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0068_state_message'),
        ('metrics', '0006_alter_dailygoldbystate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoldbystate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailygoldbystate_state', to='state.state', verbose_name='Государство'),
        ),
    ]
