# Generated by Django 3.2.18 on 2024-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_alter_dailygoldbystate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoldbystate',
            name='daily_gold',
            field=models.BigIntegerField(default=0, verbose_name='Добыто после дейлика'),
        ),
    ]
