# Generated by Django 3.1.3 on 2022-10-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava_border', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaborder',
            name='image',
        ),
        migrations.AddField(
            model_name='avaborder',
            name='shape',
            field=models.TextField(default='', verbose_name='Рамка'),
        ),
    ]
