# Generated by Django 3.1.3 on 2022-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava_border', '0002_auto_20221025_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaborder',
            name='box_x',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='первое значение бокса'),
        ),
        migrations.AddField(
            model_name='avaborder',
            name='box_y',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='второе значение бокса'),
        ),
    ]
