# Generated by Django 3.1.3 on 2023-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava_border', '0004_avaborder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaborderownership',
            name='png_use',
            field=models.BooleanField(default=False, verbose_name='PNG'),
        ),
    ]
