# Generated by Django 3.1.3 on 2022-01-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Вариант опроса', 'verbose_name_plural': 'Варианты опросов'},
        ),
    ]
