# Generated by Django 3.1.3 on 2022-01-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220127_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
