# Generated by Django 3.1.3 on 2022-01-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='poll',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='polls.poll', verbose_name='Опрос'),
        ),
    ]
