# Generated by Django 3.1.3 on 2020-12-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_auto_20201204_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='rnd_mineral',
        ),
    ]
