# Generated by Django 3.1.3 on 2020-12-11 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_remove_region_rnd_mineral'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='gold_cap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Золото: максимум'),
        ),
        migrations.AddField(
            model_name='region',
            name='gold_has',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Золото: в наличии'),
        ),
    ]
