# Generated by Django 3.1.3 on 2021-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_auto_20201211_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='east',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='region',
            name='is_east',
            field=models.BooleanField(default=True, verbose_name='Восточной долготы'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_north',
            field=models.BooleanField(default=True, verbose_name='Северной широты'),
        ),
        migrations.AddField(
            model_name='region',
            name='north',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
