# Generated by Django 3.1.3 on 2021-01-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_auto_20210109_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.IntegerField(default=0, verbose_name='Широта - центр'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.IntegerField(default=0, verbose_name='Долгота - центр'),
        ),
        migrations.AddField(
            model_name='region',
            name='shape',
            field=models.TextField(default='', verbose_name='Вид на карте'),
        ),
        migrations.AddField(
            model_name='region',
            name='zoom',
            field=models.IntegerField(default=1, verbose_name='Масштаб карты'),
        ),
    ]
