# Generated by Django 3.1.3 on 2021-01-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_auto_20210122_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9, verbose_name='Широта - центр'),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9, verbose_name='Долгота - центр'),
        ),
    ]
