# Generated by Django 3.1.3 on 2021-01-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        ('region', '0008_auto_20210122_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_state', to='state.state', verbose_name='Государство'),
        ),
    ]
