# Generated by Django 3.1.3 on 2021-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0009_region_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='on_map_id',
            field=models.CharField(default='MOS-MOS', max_length=50, verbose_name='ID на карте'),
            preserve_default=False,
        ),
    ]
