# Generated by Django 3.1.3 on 2021-02-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0010_region_on_map_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='grokcite_proc',
            new_name='bauxite_proc',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='anohor_proc',
            new_name='coal_proc',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='berkonor_proc',
            new_name='iron_proc',
        ),
    ]
