# Generated by Django 3.1.3 on 2021-02-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0011_auto_20210203_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='east',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Широта - центр'),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Долгота - центр'),
        ),
        migrations.AlterField(
            model_name='region',
            name='north',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
