# Generated by Django 3.1.3 on 2021-03-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0012_auto_20210212_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='bauxite_proc',
            field=models.IntegerField(default=25, verbose_name='Процент бокситов'),
        ),
        migrations.AlterField(
            model_name='region',
            name='coal_proc',
            field=models.IntegerField(default=25, verbose_name='Процент угля'),
        ),
        migrations.AlterField(
            model_name='region',
            name='iron_proc',
            field=models.IntegerField(default=25, verbose_name='Процент железа'),
        ),
    ]
