# Generated by Django 3.1.3 on 2021-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0013_auto_20210312_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='med_top',
            field=models.IntegerField(default=1, verbose_name='Рейтинг госпиталя'),
        ),
    ]
