# Generated by Django 3.1.3 on 2021-10-14 08:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0014_region_med_top'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='region',
            managers=[
                ('with_off', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='is_off',
            field=models.BooleanField(default=False, verbose_name='Выключен'),
        ),
    ]
