# Generated by Django 3.1.3 on 2021-11-26 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0015_auto_20211014_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='cash_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Деньги: налог'),
        ),
        migrations.AddField(
            model_name='region',
            name='oil_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Нефть: налог'),
        ),
        migrations.AddField(
            model_name='region',
            name='ore_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Руда: налог'),
        ),
        migrations.AddField(
            model_name='region',
            name='prod_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Производство: налог'),
        ),
    ]
