# Generated by Django 3.1.3 on 2022-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0017_auto_20211128_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='med_lvl',
            field=models.IntegerField(default=0, verbose_name='Уровень госпиталя'),
        ),
    ]
