# Generated by Django 3.1.3 on 2022-04-02 11:33

from django.db import migrations

def create_hospitals(apps, schema_editor):
    Region = apps.get_model("region", "Region")
    Hospital = apps.get_model("region", "Hospital")
    
    for region in Region.objects.filter(med_lvl__gt=0):
        Hospital.objects.create(region=region, level=region.med_lvl, top=region.med_top)
    

class Migration(migrations.Migration):

    dependencies = [
        ('region', '0021_auto_20220402_1515'),
    ]

    operations = [
        migrations.RunPython(create_hospitals),
    ]
