# Generated by Django 3.1.3 on 2022-04-02 12:15

from django.db import migrations
import django.db.models.manager
import region.actual_manager


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0019_hospital'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='region',
            managers=[
                ('with_off', django.db.models.manager.Manager()),
                ('objects', region.actual_manager.ActualManager()),
            ],
        ),
    ]
