# Generated by Django 3.1.3 on 2022-04-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0020_auto_20220402_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='med_lvl',
        ),
        migrations.RemoveField(
            model_name='region',
            name='med_top',
        ),
    ]
