# Generated by Django 3.1.3 on 2022-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0022_powerplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerplant',
            name='level_on',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Вкл. уровень здания'),
        ),
    ]
