# Generated by Django 3.1.3 on 2022-07-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0023_powerplant_level_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerplant',
            name='level_on',
        ),
    ]
