# Generated by Django 3.1.3 on 2022-10-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0024_remove_powerplant_level_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень здания')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион строительства')),
            ],
            options={
                'verbose_name': 'Укрепления',
                'verbose_name_plural': 'Укрепления',
            },
        ),
    ]
