# Generated by Django 3.1.3 on 2022-11-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0025_defences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='oil_type',
            field=models.CharField(choices=[('wti_oil', 'WTI'), ('brent_oil', 'Brent'), ('urals_oil', 'Urals')], default='urals_oil', max_length=10),
        ),
    ]
