# Generated by Django 3.1.3 on 2023-01-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0026_auto_20221127_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='gold_depletion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Истощение'),
        ),
        migrations.AddField(
            model_name='region',
            name='oil_depletion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='истощение'),
        ),
        migrations.AddField(
            model_name='region',
            name='ore_depletion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='истощение'),
        ),
    ]
