# Generated by Django 3.1.3 on 2023-01-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0027_auto_20230119_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_map_id', models.CharField(max_length=50, verbose_name='ID на карте')),
                ('shape', models.TextField(default='', verbose_name='Вид на карте')),
                ('zoom', models.IntegerField(default=1, verbose_name='Масштаб карты')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_map', to='region.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Контур',
                'verbose_name_plural': 'Контуры на карте',
            },
        ),
    ]
