# Generated by Django 3.1.3 on 2023-01-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    def create_shapes(apps, schema_editor):
        Region = apps.get_model('region', 'Region')
        MapShape = apps.get_model('region', 'MapShape')
        
        for region in Region.with_off.all():
            shape = MapShape(
                region=region,
                on_map_id=region.on_map_id,
                shape=region.shape,
                zoom=region.zoom,
            )
            shape.save()

    dependencies = [
        ('region', '0028_mapshape'),
    ]

    operations = [
        migrations.RunPython(create_shapes),
    ]
