# Generated by Django 3.1.3 on 2023-01-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0029_auto_20230131_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='on_map_id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='region',
            name='zoom',
        ),
    ]
