# Generated by Django 3.1.3 on 2023-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0030_auto_20230131_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='on_map_id',
            field=models.CharField(default='', max_length=50, verbose_name='ID на карте'),
        ),
    ]
