# Generated by Django 3.1.3 on 2023-01-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    def create_shapes(apps, schema_editor):
        MapShape = apps.get_model('region', 'MapShape')
        
        for shape in MapShape.objects.all():
            shape.region.on_map_id = shape.on_map_id
            shape.region.save()

    dependencies = [
        ('region', '0031_region_on_map_id'),
    ]

    operations = [
        migrations.RunPython(create_shapes),
    ]
