# Generated by Django 3.1.3 on 2023-01-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0032_auto_20230131_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapshape',
            name='on_map_id',
        ),
    ]
