# Generated by Django 3.1.3 on 2023-05-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0060_auto_20230506_0428'),
        ('region', '0033_remove_mapshape_on_map_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='oil_mark',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.good', verbose_name='Нефть'),
        ),
    ]
