# Generated by Django 3.1.3 on 2023-05-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    def move_stocks(apps, schema_editor):
        Good = apps.get_model('storage', 'Good')
        Region = apps.get_model('region', 'Region')
        
        oil_types = {
            'wti_oil': 'Нефть WTI',
            'brent_oil': 'Нефть Brent',
            'urals_oil': 'Нефть Urals',
        }     

        oil_dict = {}
                    
        
        for region in Region.with_off.all():
            
            if not region.oil_type in oil_dict:
                good = Good.objects.get(name=oil_types[region.oil_type])
                oil_dict[region.oil_type] = good
                
            else:
                good = oil_dict[region.oil_type]
                
            region.oil_mark = good
            region.save()
            
        
    dependencies = [
        ('region', '0034_region_oil_mark'),
    ]

    operations = [
        migrations.RunPython(move_stocks)
    ]
