# Generated by Django 3.1.3 on 2023-05-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0060_auto_20230506_0428'),
        ('region', '0035_auto_20230509_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fossils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=25, verbose_name='Процент')),
                ('good', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Руда')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Ископаемое',
                'verbose_name_plural': 'Ископаемые',
            },
        ),
    ]
