# Generated by Django 3.1.3 on 2023-07-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0037_auto_20230514_0034'),
        ('region', '0035_auto_20230627_1742'),
    ]

    operations = [
    ]
