# Generated by Django 3.1.3 on 2023-11-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0024_eventwar_graph'),
        ('region', '0039_auto_20230909_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рельеф',
                'verbose_name_plural': 'Рельефы',
            },
        ),
        migrations.CreateModel(
            name='TerrainModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Модификатор')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.terrain', verbose_name='Рельеф')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='war.unit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Модификатор рельефа',
                'verbose_name_plural': 'Модификаторы рельефа',
            },
        ),
    ]
