# Generated by Django 3.1.3 on 2023-11-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0040_terrain_terrainmodifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='terrain',
            field=models.ManyToManyField(blank=True, related_name='terrain', to='region.Terrain', verbose_name='Рельеф'),
        ),
    ]
