# Generated by Django 3.1.3 on 2023-11-18 23:22

from django.db import migrations


def set_holmy(apps, schema_editor):
    
    Region = apps.get_model("region", "Region")
    Terrain = apps.get_model("region", "Terrain")
    
    h_terrain = None
    
    if not Terrain.objects.filter(title='Холмы').exists():
        h_terrain = Terrain(
                            title = 'Холмы'
                            )
        h_terrain.save()
    
    regions = Region.objects.all()
    
    for region in regions:
        region.terrain.add(h_terrain)
        region.save()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('region', '0041_region_terrain'),
    ]

    operations = [
        migrations.RunPython(set_holmy),
    ]
