# Generated by Django 3.1.3 on 2023-12-07 14:56

from django.db import migrations


def recount_defence(apps, schema_editor):

    Defences = apps.get_model("region", "Defences")
    Treasury = apps.get_model("state", "Treasury")
    TreasuryStock = apps.get_model("state", "TreasuryStock")
    Good = apps.get_model("storage", "Good")

    for defence in Defences.objects.all():
        if defence.region.state:
            treasury = Treasury.objects.get(state=defence.region.state)

            treasury.cash += defence.level * 500

            good = Good.objects.get(name_ru='Сталь')
            if TreasuryStock.objects.filter(treasury=treasury, good=good).exists():
                stock = TreasuryStock.objects.get(treasury=treasury, good=good)
                stock.stock += defence.level * 10
                stock.save()
            else:
                stock = TreasuryStock(treasury=treasury, good=good)
                stock.stock = defence.level * 10
                stock.save()


            good = Good.objects.get(name_ru='Уголь')
            if TreasuryStock.objects.filter(treasury=treasury, good=good).exists():
                stock = TreasuryStock.objects.get(treasury=treasury, good=good)
                stock.stock += defence.level * 50
                stock.save()
            else:
                stock = TreasuryStock(treasury=treasury, good=good)
                stock.stock = defence.level * 50
                stock.save()

            treasury.save()

class Migration(migrations.Migration):

    dependencies = [
        ('region', '0042_auto_20231119_0222'),
    ]

    operations = [
        migrations.RunPython(recount_defence),
    ]
