# Generated by Django 3.1.3 on 2023-12-07 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0043_auto_20231207_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='peace_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Мирное время, до'),
        ),
    ]
