# Generated by Django 3.1.3 on 2024-04-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0065_auto_20240305_0121'),
        ('region', '0045_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=False, verbose_name='Используется')),
                ('plane', models.CharField(choices=[('pretender', 'pretender'), ('trickster', 'trickster')], max_length=10)),
                ('color', models.CharField(choices=[('1', 'базовый'), ('green', 'зелёный')], max_length=10)),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Самолёт',
                'verbose_name_plural': 'Самолёты',
            },
        ),
    ]
