# Generated by Django 3.1.3 on 2024-05-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0051_auto_20240522_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='color',
            field=models.CharField(choices=[('base', 'базовый'), ('red', 'красный'), ('orange', 'оранжевый'), ('yellow', 'желтый'), ('green', 'зелёный'), ('light_blue', 'голубой'), ('dark_blue', 'синий'), ('violet', 'фиолетовый'), ('pink', 'розовый'), ('black', 'чёрный'), ('gold', 'золотой'), ('dreamflight', 'Dreamflight'), ('black_gold', 'чёрно-золотой'), ('green_cam', 'зелёный камуфляж'), ('blue_cam', 'синий камуфляж'), ('desert_cam', 'песочный камуфляж'), ('wood', 'дерево'), ('pobeda', 'пузырьки')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plane',
            name='plane',
            field=models.CharField(choices=[('nagger', 'Nagger'), ('pretender', 'Pretender'), ('trickster', 'Trickster'), ('smuggler', 'Smuggler'), ('chaser', 'Chaser'), ('reaper', 'Reaper'), ('cheater', 'Cheater'), ('carrier', 'Carrier'), ('observer', 'Observer'), ('striker', 'Striker'), ('demolisher', 'Demolisher'), ('sprinter', 'Sprinter'), ('harrier', 'Harrier'), ('sailor', 'Sailor'), ('hammer', 'Hammer')], max_length=10),
        ),
    ]
