# Generated by Django 3.1.3 on 2024-05-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0054_auto_20240601_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Никнейм'),
        ),
    ]
