# Generated by Django 3.2.18 on 2024-09-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0057_auto_20240619_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_name_az',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_be',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_de',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_es',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ind',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_lv',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_pl',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_pt_br',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ru',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_tr',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_uk',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
    ]
