# Generated by Django 3.2.18 on 2024-09-06 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0058_auto_20240905_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='joined_since',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 4, 0, 0), verbose_name='В составе с'),
        ),
    ]
