# Generated by Django 3.2.18 on 2024-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0059_region_joined_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='color',
            field=models.CharField(choices=[('base', 'базовый'), ('red', 'красный'), ('orange', 'оранжевый'), ('yellow', 'желтый'), ('green', 'зелёный'), ('light_blue', 'голубой'), ('dark_blue', 'синий'), ('violet', 'фиолетовый'), ('pink', 'розовый'), ('black', 'чёрный'), ('gold', 'золотой'), ('black_gold', 'чёрно-золотой'), ('wood', 'дерево'), ('dreamflight', 'Dreamflight'), ('android', 'Android tester'), ('hexagon', 'гексагон'), ('standard', 'стандартная схема'), ('green_cam', 'зелёный камуфляж'), ('white_cam', 'белый камуфляж'), ('green_white_cam', 'бело-зелёный камуфляж'), ('blue_cam', 'синий камуфляж'), ('desert_cam', 'песочный камуфляж'), ('corny', 'царь полей'), ('redline', 'красная линия'), ('airball', 'Airball'), ('pobeda', 'пузырьки')], max_length=20),
        ),
    ]
