# Generated by Django 3.2.18 on 2024-10-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0061_alter_plane_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerplant',
            options={'verbose_name': 'ТЭЦ', 'verbose_name_plural': 'Электростанции'},
        ),
    ]
