# Generated by Django 3.2.18 on 2024-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0062_alter_powerplant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_name_fr',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_it',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_sr',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
    ]
