# Generated by Django 3.2.18 on 2024-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0063_auto_20241028_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_name_hy',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Название региона'),
        ),
    ]
