# Generated by Django 3.2.18 on 2024-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0065_alter_plane_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=2, verbose_name='Код страны')),
                ('regions', models.ManyToManyField(blank=True, related_name='regions', to='region.Region', verbose_name='Регионы')),
            ],
            options={
                'verbose_name': 'Спавн',
                'verbose_name_plural': 'Спавны',
            },
        ),
    ]
