# Generated by Django 3.1.3 on 2022-03-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0013_goldlog'),
        ('state', '0030_auto_20220307_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pres_leader', to='player.player', verbose_name='Президент')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pres_state', to='state.state', verbose_name='Государство')),
            ],
            options={
                'verbose_name': 'Президент',
                'verbose_name_plural': 'Президенты',
            },
        ),
    ]
