# Generated by Django 3.1.3 on 2022-03-13 20:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('player', '0013_goldlog'),
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentialVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Идут сейчас')),
                ('voting_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('voting_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gov.president', verbose_name='Должность')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Выборы президента',
                'verbose_name_plural': 'Выборы президента',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='player.player', verbose_name='Кандидат')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Голосовавший')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gov.presidentialvoting', verbose_name='Выборы')),
            ],
            options={
                'verbose_name': 'Бюллетень президентских выборов',
                'verbose_name_plural': 'Бюллетени президентских выборов',
            },
        ),
    ]
