# Generated by Django 3.1.3 on 2022-03-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_goldlog'),
        ('gov', '0003_president_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentialvoting',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='presidentialvoting_candidates', to='player.Player', verbose_name='Кандидаты'),
        ),
    ]
