# Generated by Django 3.1.3 on 2022-05-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0038_auto_20220502_1850'),
        ('player', '0020_player_cards_count'),
        ('gov', '0004_presidentialvoting_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minister', to='player.player', verbose_name='Игрок')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minist_state', to='state.state', verbose_name='Государство')),
            ],
            options={
                'verbose_name': 'Министр',
                'verbose_name_plural': 'Министры',
            },
        ),
    ]
