# Generated by Django 3.1.3 on 2022-05-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0005_minister'),
    ]

    operations = [
        migrations.AddField(
            model_name='minister',
            name='post_name',
            field=models.CharField(default='МИД', max_length=30, verbose_name='Название должности'),
        ),
    ]
