# Generated by Django 3.1.3 on 2022-05-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0020_player_cards_count'),
        ('state', '0038_auto_20220502_1850'),
        ('gov', '0006_minister_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minister',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minister', to='player.player', verbose_name='Игрок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='minister',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minist_state', to='state.state', verbose_name='Государство'),
        ),
    ]
