# Generated by Django 3.1.3 on 2022-05-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0038_auto_20220502_1850'),
        ('gov', '0007_auto_20220508_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisterRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(choices=[('ChangeCoat', 'Новый герб государства'), ('ChangeTaxes', 'Изменение налогов'), ('ChangeTitle', 'Переименование государства'), ('Construction', 'Строительство'), ('ExploreResources', 'Разведка ресурсов'), ('PurchaseAuction', 'Закупка товаров'), ('ChangeForm', 'Новая форма правления государства')], max_length=20)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_right_state', to='state.state', verbose_name='Государство')),
            ],
            options={
                'verbose_name': 'Право министра',
                'verbose_name_plural': 'Права министров',
            },
        ),
    ]
