# Generated by Django 3.1.3 on 2022-05-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0008_ministerright'),
    ]

    operations = [
        migrations.AddField(
            model_name='minister',
            name='rights',
            field=models.ManyToManyField(blank=True, related_name='rights', to='gov.MinisterRight', verbose_name='Права'),
        ),
    ]
