# Generated by Django 3.1.3 on 2022-05-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0009_minister_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministerright',
            name='state',
        ),
    ]
