# Generated by Django 3.1.3 on 2022-08-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_playersettings'),
        ('region', '0024_remove_powerplant_level_on'),
        ('gov', '0014_auto_20220801_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidencyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('char', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char', to='player.player', verbose_name='Персонаж')),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_region', to='region.region', verbose_name='Регион запроса')),
            ],
            options={
                'verbose_name': 'Запрос прописки',
                'verbose_name_plural': 'Запросы прописки',
            },
        ),
    ]
