# Generated by Django 3.1.3 on 2022-08-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0015_residencyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencyrequest',
            name='deleted',
        ),
    ]
