# Generated by Django 3.1.3 on 2022-10-30 20:24

from django.db import migrations
from django.utils import timezone
import datetime

from state.tasks import finish_presidential


def crontask_finish(apps, schema_editor):
    
    PresidentialVoting = apps.get_model("gov", "PresidentialVoting")
    
    for voting in PresidentialVoting.objects.filter(voting_start__lt=timezone.now() - datetime.timedelta(days=1), running=True):
        
        finish_presidential(voting.president.pk)
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0020_auto_20221022_0100'),
    ]

    operations = [
        migrations.RunPython(crontask_finish),
    ]
