# Generated by Django 3.1.3 on 2022-11-03 10:59

from django.db import migrations
from django.utils import timezone
import datetime

from state.tasks import finish_presidential


def crontask_start(apps, schema_editor):
    
    finish_presidential(13)

class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0024_auto_20221102_1509'),
    ]

    operations = [
        migrations.RunPython(crontask_start),
    ]
