# Generated by Django 3.1.3 on 2023-11-11 21:35

from django.db import migrations, models
import django.utils.timezone


def set_weekday(apps, schema_editor):

    ChangeForm = apps.get_model("bill", "ChangeForm")
    
    President = apps.get_model("gov", "President")
    Parliament = apps.get_model("state", "Parliament")
    
    
    leaders = President.objects.all()
    
    for leader in leaders:
        leader.elections_day = 0
        leader.foundation_date = django.utils.timezone.now()
    
        if Parliament.objects.filter(state=leader.state).exists():
        
            parl = Parliament.objects.get(state=leader.state)
            
            if ChangeForm.objects.filter(
                                            parliament=parl,
                                            running=False,
                                            type='ac').exists():
                                            
                bill = ChangeForm.objects.order_by('-voting_end').filter(
                                            parliament=parl,
                                            running=False,
                                            type='ac')[0]
                                            
                leader.foundation_date = bill.voting_end
                leader.elections_day = bill.voting_end.weekday()
                
            
        leader.save()
    
            
            
def clear_tasks(apps, schema_editor):

    President = apps.get_model("gov", "President")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    
    parties = President.objects.all()
    
    for party in parties:
    
        if party.task:
        
            task_id = party.task.pk
            party.task = None
            party.save()

            PeriodicTask.objects.filter(pk=task_id).delete()
            
    
    PresidentialVoting = apps.get_model("gov", "PresidentialVoting")
    
    parties = PresidentialVoting.objects.all()
    
    for party in parties:
    
        if party.task:
        
            task_id = party.task.pk
            party.task = None
            party.save()

            PeriodicTask.objects.filter(pk=task_id).delete()
            
        

class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0034_auto_20230911_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='president',
            name='elections_day',
            field=models.IntegerField(default=0, verbose_name='День выборов'),
        ),
        migrations.AddField(
            model_name='president',
            name='foundation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        
        migrations.RunPython(clear_tasks),
        migrations.RunPython(set_weekday),
    ]
