# Generated by Django 3.1.3 on 2024-04-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0038_auto_20240222_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministerright',
            name='right',
            field=models.CharField(choices=[('ChangeCoat', 'Новый герб государства'), ('ChangeTaxes', 'Изменение налогов'), ('ChangeTitle', 'Переименование государства'), ('Construction', 'Строительство'), ('ExploreResources', 'Разведка ресурсов'), ('PurchaseAuction', 'Закупка товаров'), ('ChangeForm', 'Новая форма правления государства'), ('ChangeResidency', 'Новый способ выдачи прописки'), ('StartWar', 'Объявление войны'), ('Independence', 'Объявление независимости'), ('TransferRegion', 'Объявление независимости'), ('ForeignRights', 'Министр иностранных дел'), ('MiningStats', 'Статистика добычи')], max_length=20),
        ),
    ]
