# Generated by Django 3.1.3 on 2020-12-25 15:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0005_auto_20201211_2032'),
        ('party', '0006_membershiplog'),
        ('player', '0003_auto_20201213_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Парламент',
                'verbose_name_plural': 'Парламенты',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название государства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/state_avatars/', verbose_name='Герб')),
                ('color', models.CharField(default='008542', max_length=6, verbose_name='Цвет государства')),
                ('foundation_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('parl', 'Парламентская республика'), ('pres', 'Президентская республика')], default='parl', max_length=4)),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Государство',
                'verbose_name_plural': 'Государства',
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steel', models.IntegerField(default=0, verbose_name='steel')),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_placement', to='region.region', verbose_name='Регион размещения')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_state', to='state.state', verbose_name='Государство')),
            ],
            options={
                'verbose_name': 'Казна',
                'verbose_name_plural': 'Казны',
            },
        ),
        migrations.CreateModel(
            name='ParliamentVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Идут сейчас')),
                ('voting_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('voting_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliament', verbose_name='Парламент')),
            ],
            options={
                'verbose_name': 'Выборы',
                'verbose_name_plural': 'Выборы',
            },
        ),
        migrations.CreateModel(
            name='ParliamentParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliament', verbose_name='Парламент')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Партия парламента')),
            ],
            options={
                'verbose_name': 'Парламентская партия',
                'verbose_name_plural': 'Парламентские партии',
            },
        ),
        migrations.AddField(
            model_name='parliament',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='state.state', verbose_name='Государство'),
        ),
        migrations.CreateModel(
            name='DeputyMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliament', verbose_name='Заседает в парламенте')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Представляет партию')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Депутат')),
            ],
            options={
                'verbose_name': 'Мандат',
                'verbose_name_plural': 'Мандаты',
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Кандидат')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Голосовавший')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliamentvoting', verbose_name='Выборы')),
            ],
            options={
                'verbose_name': 'Бюллетень',
                'verbose_name_plural': 'Бюллетени',
            },
        ),
    ]
