# Generated by Django 3.1.3 on 2021-10-07 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='foundation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
