# Generated by Django 3.1.3 on 2021-10-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('state', '0003_auto_20211007_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliament',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='parliamentvoting',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask'),
        ),
    ]
