# Generated by Django 3.1.3 on 2021-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_auto_20211008_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='aluminium',
            field=models.IntegerField(default=0, verbose_name='alumunuim'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='antitank',
            field=models.IntegerField(default=0, verbose_name='antitank'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='bauxite',
            field=models.IntegerField(default=0, verbose_name='bauxite'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='brent_oil',
            field=models.IntegerField(default=0, verbose_name='brent_oil'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='cash',
            field=models.BigIntegerField(default=0, verbose_name='storage_cash'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='coal',
            field=models.IntegerField(default=0, verbose_name='Уголь'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='diesel',
            field=models.IntegerField(default=0, verbose_name='diesel'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='gas',
            field=models.IntegerField(default=0, verbose_name='gas'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='iron',
            field=models.IntegerField(default=0, verbose_name='iron'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='jet',
            field=models.IntegerField(default=0, verbose_name='attack_air'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='pzrk',
            field=models.IntegerField(default=0, verbose_name='mpads'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='station',
            field=models.IntegerField(default=0, verbose_name='orb_station'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='tank',
            field=models.IntegerField(default=0, verbose_name='tank'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='urals_oil',
            field=models.IntegerField(default=0, verbose_name='urals_oil'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='wti_oil',
            field=models.IntegerField(default=0, verbose_name='wti_oil'),
        ),
    ]
