# Generated by Django 3.1.3 on 2021-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_auto_20211020_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='rifle',
            field=models.IntegerField(default=0, verbose_name='Автоматы'),
        ),
    ]
