# Generated by Django 3.1.3 on 2021-10-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0007_treasury_rifle'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='howitzer',
            field=models.IntegerField(default=0, verbose_name='howitzer'),
        ),
    ]
