# Generated by Django 3.1.3 on 2021-11-28 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0010_auto_20211126_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='prod_tax',
        ),
        migrations.AddField(
            model_name='state',
            name='trade_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Торговля: налог'),
        ),
    ]
