# Generated by Django 3.1.3 on 2021-11-30 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0017_auto_20211128_1440'),
        ('player', '0011_auto_20211126_2024'),
        ('state', '0011_auto_20211128_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Рассматривается')),
                ('type', models.CharField(blank=True, choices=[('ac', 'Принят'), ('rj', 'Отклонён'), ('cn', 'Отменён')], default=None, max_length=2, null=True, verbose_name='Решение')),
                ('cash_cost', models.BigIntegerField(default=0, verbose_name='Наличные')),
                ('voting_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Время начала рассмотрения')),
                ('voting_end', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True, verbose_name='Время завершения рассмотрения')),
                ('task_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='id фонового процесса')),
                ('resource', models.CharField(blank=True, choices=[('gold', 'gold'), ('oil', 'oil'), ('ore', 'ore')], default=None, max_length=4, null=True, verbose_name='Ресурс')),
                ('exp_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Объем разведки')),
                ('initiator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player', verbose_name='Инициатор')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.parliament', verbose_name='Закон в парламенте')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион разведки')),
                ('votes_con', models.ManyToManyField(blank=True, related_name='exploreresources_votes_con', to='player.Player', verbose_name='Голоса "против"')),
                ('votes_pro', models.ManyToManyField(blank=True, related_name='exploreresources_votes_pro', to='player.Player', verbose_name='Голоса "за"')),
            ],
            options={
                'verbose_name': 'Разведка ресурсов',
                'verbose_name_plural': 'Разведки ресурсов',
            },
        ),
    ]
