# Generated by Django 3.1.3 on 2021-12-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('state', '0012_exploreresources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploreresources',
            name='task_id',
        ),
        migrations.AddField(
            model_name='exploreresources',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='exploreresources',
            name='resource',
            field=models.CharField(blank=True, choices=[('gold', 'Золото'), ('oil', 'Нефть'), ('ore', 'Руда')], default=None, max_length=4, null=True, verbose_name='Ресурс'),
        ),
    ]
