# Generated by Django 3.1.3 on 2021-12-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0013_auto_20211202_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Койки'),
        ),
    ]
