# Generated by Django 3.1.3 on 2021-12-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0014_treasury_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='plastic',
            field=models.IntegerField(default=0, verbose_name='plastic'),
        ),
    ]
