# Generated by Django 3.1.3 on 2021-12-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0016_purchaseauction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseauction',
            name='max_sum',
        ),
    ]
