# Generated by Django 3.1.3 on 2021-12-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0017_remove_purchaseauction_max_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_good', models.CharField(choices=[('cash', 'Наличные'), ('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Койки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП')], default=None, max_length=10)),
                ('lock_count', models.BigIntegerField(default=0, verbose_name='Количество')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('lock_treasury', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lock_storage', to='state.treasury', verbose_name='Казна')),
            ],
            options={
                'verbose_name': 'Блокировка Казны',
                'verbose_name_plural': 'Блокировки Казны',
            },
        ),
    ]
