# Generated by Django 3.1.3 on 2021-12-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0018_treasurylock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurylock',
            name='lock_good',
            field=models.CharField(choices=[('cash', 'Наличные'), ('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Койки'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП')], default=None, max_length=10, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='treasurylock',
            name='lock_treasury',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lock_treasury', to='state.treasury', verbose_name='Казна'),
        ),
    ]
