# Generated by Django 3.1.3 on 2022-01-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0020_construction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construction',
            options={'verbose_name': 'Строительство', 'verbose_name_plural': 'Строительства'},
        ),
    ]
