# Generated by Django 3.1.3 on 2022-01-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0022_changetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetitle',
            name='new_title',
            field=models.CharField(max_length=50, verbose_name='Название государства'),
        ),
        migrations.AlterField(
            model_name='state',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название государства'),
        ),
    ]
