# Generated by Django 3.1.3 on 2022-02-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0024_changecoat'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='actualize_dtime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата акутализации'),
        ),
    ]
