# Generated by Django 3.1.3 on 2022-03-03 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0027_auto_20220302_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changetaxes',
            name='everywhere',
        ),
        migrations.AddField(
            model_name='changetaxes',
            name='new_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Новый налог'),
        ),
    ]
