# Generated by Django 3.1.3 on 2022-03-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0029_changetaxes_old_tax'),
    ]

    database_operations = [migrations.AlterModelTable('PurchaseAuction', 'bill_purchaseauction'),
                            migrations.AlterModelTable('ExploreResources', 'bill_exploreresources'),
                            migrations.AlterModelTable('Construction', 'bill_construction'),
                            migrations.AlterModelTable('ChangeTitle', 'bill_changetitle'),
                            migrations.AlterModelTable('ChangeTaxes', 'bill_changetaxes'),
                            migrations.AlterModelTable('ChangeCoat', 'bill_changecoat'),
                        ]

    state_operations = [
        migrations.DeleteModel('PurchaseAuction'),
        migrations.DeleteModel('ExploreResources'),
        migrations.DeleteModel('Construction'),
        migrations.DeleteModel('ChangeTitle'),
        migrations.DeleteModel('ChangeTaxes'),
        migrations.DeleteModel('ChangeCoat'),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]