# Generated by Django 3.1.3 on 2022-03-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0030_auto_20220307_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='type',
            field=models.CharField(choices=[('Temporary', 'Временное правительство'), ('Presidential', 'Президентская республика')], default='Temporary', max_length=15),
        ),
    ]
