# Generated by Django 3.1.3 on 2022-03-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0031_auto_20220313_2007'),
    ]
        
    def change_regime(apps, schema_editor):
        State = apps.get_model('state', 'State')
        
        for state in State.objects.all():
            state.type = 'Temporary'
            state.save()

    operations = [
        migrations.RunPython(change_regime),
    ]

