# Generated by Django 3.1.3 on 2022-04-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0033_auto_20220408_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='power_actualize',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Акутализация электросети'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='power_on',
            field=models.BooleanField(default=False, verbose_name='Электроскть работает'),
        ),
    ]
