# Generated by Django 3.1.3 on 2022-04-14 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0034_auto_20220414_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='actualize_dtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата акутализации'),
        ),
    ]
