# Generated by Django 3.1.3 on 2022-05-02 15:50

from django.db import migrations

def create_mandates(apps, schema_editor):
    Parliament = apps.get_model("state", "Parliament")
    DeputyMandate = apps.get_model("state", "DeputyMandate")
    President = apps.get_model("gov", "President")
    
    for pres in President.objects.all():
    
        parl = Parliament.objects.get(state=pres.state)
        if DeputyMandate.objects.filter(player=pres.leader).exists():
            DeputyMandate.objects.filter(player=pres.leader).update(player=None)
        
        DeputyMandate.objects.create(player=pres.leader, parliament=parl, is_president=True)


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0037_auto_20220502_1807'),
    ]

    operations = [
      migrations.RunPython(create_mandates),
    ]
