# Generated by Django 3.1.3 on 2022-08-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0040_auto_20220806_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='drone',
            field=models.IntegerField(default=0, verbose_name='drone'),
        ),
    ]
