# Generated by Django 3.1.3 on 2022-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0044_auto_20221008_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliamentvoting',
            name='running',
            field=models.BooleanField(default=True, verbose_name='Идут сейчас'),
        ),
    ]
