# Generated by Django 3.1.3 on 2022-10-28 19:39

from django.db import migrations
from django.utils import timezone
import datetime

from state.tasks import finish_elections



def crontask_finish(apps, schema_editor):
    
    ParliamentVoting = apps.get_model("state", "ParliamentVoting")
    
    for voting in ParliamentVoting.objects.filter(voting_start__lt=timezone.now() - datetime.timedelta(days=1), running=True):
        
        finish_elections(voting.parliament.pk)
        

class Migration(migrations.Migration):

    dependencies = [
        ('state', '0046_auto_20221022_0006'),
    ]

    operations = [
        migrations.RunPython(crontask_finish),
    ]
