# Generated by Django 3.1.3 on 2022-11-04 13:26

from django.db import migrations
from django.utils import timezone
import json

def crontask_remake(apps, schema_editor):

    Parliament = apps.get_model("state", "Parliament")
    ParliamentVoting = apps.get_model("state", "ParliamentVoting")    
    
    parlaments = Parliament.objects.all()
    
    for parl in parlaments:
    
        if parl.task is not None:
            
            parl.task.name = 'Начало выборов, id парла ' + str(parl.pk)
            parl.task.save()
            
        if ParliamentVoting.objects.filter(parliament=parl, task__isnull=False).exists():
        
            voting = ParliamentVoting.objects.get(parliament=parl, task__isnull=False)
            voting.task.name = 'Конец выборов, id парла ' + str(parl.pk)
            voting.task.save()
            
            

class Migration(migrations.Migration):

    dependencies = [
        ('state', '0051_auto_20221104_1535'),
    ]

    operations = [
         migrations.RunPython(crontask_remake),
    ]
