# Generated by Django 3.1.3 on 2022-11-04 13:59

from django.db import migrations
from django.utils import timezone
import json

def crontask_remake(apps, schema_editor):

    President = apps.get_model("gov", "President")
    PresidentialVoting = apps.get_model("gov", "PresidentialVoting")
    
    presidents = President.objects.all()
    
    for president in presidents:
    
        if president.task is not None:
            
            president.task.name = 'Начало выборов, id преза ' + str(president.pk)
            president.task.save()
            
        if PresidentialVoting.objects.filter(president=president, task__isnull=False).exists():
        
            voting = PresidentialVoting.objects.get(president=president, task__isnull=False)
            voting.task.name = 'Конец выборов, id преза ' + str(president.pk)
            voting.task.save()            
            


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0052_auto_20221104_1626'),
    ]

    operations = [
         migrations.RunPython(crontask_remake),
    ]
