# Generated by Django 3.1.3 on 2022-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0053_auto_20221104_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='aluminium',
            field=models.IntegerField(default=0, verbose_name='Алюминий'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='antitank',
            field=models.IntegerField(default=0, verbose_name='ПТ-орудия'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='bauxite',
            field=models.IntegerField(default=0, verbose_name='Бокситы'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='brent_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Brent'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='cash',
            field=models.BigIntegerField(default=0, verbose_name='Наличные'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='diesel',
            field=models.IntegerField(default=0, verbose_name='Дизельное топливо'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='drone',
            field=models.IntegerField(default=0, verbose_name='БПЛА'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='gas',
            field=models.IntegerField(default=0, verbose_name='Бензин'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='ifv',
            field=models.IntegerField(default=0, verbose_name='БМП'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='iron',
            field=models.IntegerField(default=0, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='jet',
            field=models.IntegerField(default=0, verbose_name='Штурмовики'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='medical',
            field=models.IntegerField(default=0, verbose_name='Медикаменты'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='plastic',
            field=models.IntegerField(default=0, verbose_name='Пластик'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='power_on',
            field=models.BooleanField(default=False, verbose_name='Электросеть работает'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='pzrk',
            field=models.IntegerField(default=0, verbose_name='ПЗРК'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='station',
            field=models.IntegerField(default=0, verbose_name='Орбитальные орудия'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='steel',
            field=models.IntegerField(default=0, verbose_name='Сталь'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='tank',
            field=models.IntegerField(default=0, verbose_name='Танки'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='urals_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть Urals'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='wti_oil',
            field=models.IntegerField(default=0, verbose_name='Нефть WTI'),
        ),
        migrations.AlterField(
            model_name='treasurylock',
            name='lock_good',
            field=models.CharField(choices=[('cash', 'Наличные'), ('coal', 'Уголь'), ('iron', 'Железо'), ('bauxite', 'Бокситы'), ('wti_oil', 'Нефть WTI'), ('brent_oil', 'Нефть Brent'), ('urals_oil', 'Нефть Urals'), ('gas', 'Бензин'), ('diesel', 'Дизельное топливо'), ('plastic', 'Пластик'), ('steel', 'Сталь'), ('aluminium', 'Алюминий'), ('medical', 'Медикаменты'), ('rifle', 'Автоматы'), ('tank', 'Танки'), ('antitank', 'ПТ-орудия'), ('station', 'Орбитальные орудия'), ('jet', 'Штурмовики'), ('pzrk', 'ПЗРК'), ('ifv', 'БМП'), ('drone', 'БПЛА')], default=None, max_length=10, verbose_name='Товар'),
        ),
    ]
