# Generated by Django 3.1.3 on 2023-07-26 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0071_tradeoffer_wild_pass'),
        ('state', '0059_auto_20230329_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Запас')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.treasury', verbose_name='Казна')),
            ],
            options={
                'verbose_name': 'Запас Казны',
                'verbose_name_plural': 'Запасы Казны',
            },
        ),
    ]
