# Generated by Django 3.1.3 on 2023-07-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    def remove_locks(apps, schema_editor):
        TreasuryLock = apps.get_model('state', 'TreasuryLock')

        for lock in TreasuryLock.objects.filter(deleted=False):

            lock.lock_treasury.cash += lock.lock_count
            lock.lock_treasury.save()

        TreasuryLock.objects.all().delete()

    def move_stocks(apps, schema_editor):
        Good = apps.get_model('storage', 'Good')
        GoodLock = apps.get_model('storage', 'GoodLock')
        Treasury = apps.get_model('state', 'Treasury')
        TreasuryStock = apps.get_model('state', 'TreasuryStock')

        lock = GoodLock()

        for treasury in Treasury.objects.filter(deleted=False):

            for unit in ['coal', 'iron', 'bauxite', 'wti_oil', 'brent_oil', 'urals_oil', 'gas', 'diesel', 'plastic',
                         'steel', 'aluminium', 'medical', 'rifle', 'tank', 'mines', 'antitank', 'jet', 'pzrk', 'ifv',
                         'drone', 'drilling']:

                if getattr(treasury, unit) > 0:
                    lock.old_good = unit
                    if not TreasuryStock.objects.filter(treasury=treasury,
                                                                 good=Good.objects.get(name=lock.get_old_good_display())
                                                        ).exists():

                        stock = TreasuryStock(treasury=treasury,
                                                 good=Good.objects.get(name=lock.get_old_good_display()),
                                                stock=getattr(treasury, unit)
                                      )
                        stock.save()

                    else:
                        stock = TreasuryStock.objects.get(treasury=treasury,
                                                              good=Good.objects.get(name=lock.get_old_good_display())
                                                          )
                        stock.stock += getattr(treasury, unit)
                        stock.save()

    dependencies = [
        ('state', '0060_treasurystock'),
    ]

    operations = [
        migrations.RunPython(remove_locks),
        migrations.RunPython(move_stocks),
    ]
