# Generated by Django 3.1.3 on 2023-09-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0072_auto_20230903_1430'),
        ('state', '0061_auto_20230727_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurylock',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='Наличные'),
        ),
        migrations.AlterField(
            model_name='treasurylock',
            name='lock_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар'),
        ),
    ]
