# Generated by Django 3.1.3 on 2023-09-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0072_auto_20230903_1430'),
        ('state', '0062_auto_20230903_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurylock',
            name='lock_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар'),
        ),
    ]
