# Generated by Django 3.1.3 on 2023-11-11 17:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('state', '0063_auto_20230904_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliament',
            name='elections_day',
            field=models.IntegerField(default=0, verbose_name='День выборов'),
        ),
        
    ]
