# Generated by Django 3.1.3 on 2023-11-11 17:59

from django.db import migrations


def set_weekday(apps, schema_editor):

    Parliament = apps.get_model("state", "Parliament")
    
    parliaments = Parliament.objects.all()
    
    for parl in parliaments:
    
        parl.elections_day = parl.state.foundation_date.weekday()
    
        parl.save()       
            


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0064_parliament_elections_day'),
    ]

    operations = [
            migrations.RunPython(set_weekday),
    ]
