# Generated by Django 3.1.3 on 2023-11-11 18:00

from django.db import migrations

def clear_tasks(apps, schema_editor):

    Parliament = apps.get_model("state", "Parliament")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    
    parties = Parliament.objects.all()
    
    for party in parties:
    
        if party.task:
        
            task_id = party.task.pk
            party.task = None
            party.save()

            PeriodicTask.objects.filter(pk=task_id).delete()
            
    
    ParliamentVoting = apps.get_model("state", "ParliamentVoting")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    
    parties = ParliamentVoting.objects.all()
    
    for party in parties:
    
        if party.task:
        
            task_id = party.task.pk
            party.task = None
            party.save()

            PeriodicTask.objects.filter(pk=task_id).delete()
            

class Migration(migrations.Migration):

    dependencies = [
        ('state', '0065_auto_20231111_2059'),
    ]

    operations = [
        migrations.RunPython(clear_tasks),
    ]
