# Generated by Django 3.2.18 on 2024-10-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0067_parliament_foundation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='message',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='сообщение'),
        ),
    ]
