# Generated by Django 3.1.3 on 2022-08-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0022_playersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excavation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Промышленная экскавация',
                'verbose_name_plural': 'Промышленная экскавация',
            },
        ),
    ]
