# Generated by Django 3.1.3 on 2022-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavation',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
    ]
