# Generated by Django 3.1.3 on 2022-09-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0025_auto_20220824_0126'),
        ('skill', '0004_standardization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Режимное производство',
                'verbose_name_plural': 'Режимное производство',
            },
        ),
    ]
