# Generated by Django 3.1.3 on 2023-01-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0040_auto_20221217_1824'),
        ('skill', '0005_militaryproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scouting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Знание местности',
                'verbose_name_plural': 'Знания местности',
            },
        ),
    ]
