# Generated by Django 3.1.3 on 2023-01-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_scouting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
