# Generated by Django 3.1.3 on 2024-04-30 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0066_auto_20240418_0033'),
        ('skill', '0009_coherence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biochemistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Биохимия',
                'verbose_name_plural': 'Биохимия',
            },
        ),
    ]
