# Generated by Django 3.2.18 on 2024-08-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0086_alter_skilltraining_skill'),
        ('skill', '0010_biochemistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrophyEngineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Трофейная инженерия',
                'verbose_name_plural': 'Трофейная инженерия',
            },
        ),
    ]
