# Generated by Django 3.1.3 on 2021-10-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0008_auto_20211021_1411'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('region', '0015_auto_20211014_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('deploy', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ввод в бой')),
                ('destroy', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Уничтожение')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('rifle', models.IntegerField(default=0, verbose_name='Автоматы')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_owner', to='player.player', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Отряд пехоты',
                'verbose_name_plural': 'Отряды пехоты',
            },
        ),
        migrations.CreateModel(
            name='EventWar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Идёт война')),
                ('round', models.IntegerField(default=0, verbose_name='Раунд войны')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начало войны')),
                ('agr_dmg', models.BigIntegerField(default=0, verbose_name='Урон - атакующие')),
                ('def_dmg', models.BigIntegerField(default=0, verbose_name='Урон - оборона')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('hq_points', models.BigIntegerField(default=0, verbose_name='Прочность Штаба')),
                ('agr_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agr_region', to='region.region', verbose_name='Регион-агрессор')),
                ('def_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='def_region', to='region.region', verbose_name='Регион обороняющихся')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Тестовая война',
                'verbose_name_plural': 'Тестовые войны',
            },
        ),
    ]
