# Generated by Django 3.1.3 on 2021-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infantry',
            name='dide',
            field=models.CharField(choices=[('agr', 'Атака'), ('def', 'Оборона')], default='agr', max_length=3),
        ),
    ]
