# Generated by Django 3.1.3 on 2021-10-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0002_infantry_dide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infantry',
            old_name='dide',
            new_name='side',
        ),
    ]
