# Generated by Django 3.1.3 on 2021-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0003_auto_20211024_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwar',
            name='rifle',
            field=models.IntegerField(default=0, verbose_name='Автоматы'),
        ),
    ]
