# Generated by Django 3.1.3 on 2021-10-24 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('war', '0004_eventwar_rifle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventwar',
            name='def_dmg',
        ),
        migrations.RemoveField(
            model_name='eventwar',
            name='rifle',
        ),
        migrations.CreateModel(
            name='WarSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('agr', 'Атака'), ('def', 'Оборона')], default='agr', max_length=3)),
                ('rifle', models.IntegerField(default=0, verbose_name='Автоматы')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Сторона войны',
                'verbose_name_plural': 'Стороны войны',
            },
        ),
    ]
