# Generated by Django 3.1.3 on 2021-10-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0007_auto_20211031_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='warside',
            name='ifv',
            field=models.IntegerField(default=0, verbose_name='БМП'),
        ),
    ]
