# Generated by Django 3.1.3 on 2021-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0008_warside_ifv'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightvehicle',
            name='antitank',
            field=models.IntegerField(default=0, verbose_name='ПТ-орудия'),
        ),
    ]
