# Generated by Django 3.1.3 on 2022-08-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('player', '0022_playersettings'),
        ('war', '0011_auto_20211106_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('agr', 'Атака'), ('def', 'Оборона')], default='agr', max_length=3)),
                ('deploy', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ввод в бой')),
                ('destroy', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Уничтожение')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('drone', models.IntegerField(default=0, verbose_name='БПЛА')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='war_recon', to='player.player', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Отряд разведки',
                'verbose_name_plural': 'Отряды разведки',
            },
        ),
    ]
