# Generated by Django 3.1.3 on 2022-08-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0012_recon'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwar',
            name='recon_balance',
            field=models.FloatField(default=1, verbose_name='Баланс разведки'),
        ),
        migrations.AddField(
            model_name='warside',
            name='drone',
            field=models.IntegerField(default=0, verbose_name='Дроны'),
        ),
    ]
