# Generated by Django 3.1.3 on 2022-09-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0013_auto_20220827_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavyvehicle',
            name='deployed',
            field=models.BooleanField(default=False, verbose_name='В бою'),
        ),
        migrations.AddField(
            model_name='infantry',
            name='deployed',
            field=models.BooleanField(default=False, verbose_name='В бою'),
        ),
        migrations.AddField(
            model_name='lightvehicle',
            name='deployed',
            field=models.BooleanField(default=False, verbose_name='В бою'),
        ),
        migrations.AddField(
            model_name='recon',
            name='deployed',
            field=models.BooleanField(default=False, verbose_name='В бою'),
        ),
    ]
