# Generated by Django 3.1.3 on 2022-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0014_auto_20220924_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwar',
            name='round_log',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Последний раунд'),
        ),
    ]
