# Generated by Django 3.1.3 on 2022-10-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0025_defences'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('war', '0015_eventwar_round_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventwar',
            name='agr_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventwar_agr_region', to='region.region', verbose_name='Регион-агрессор'),
        ),
        migrations.AlterField(
            model_name='eventwar',
            name='def_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventwar_def_region', to='region.region', verbose_name='Регион обороняющихся'),
        ),
        migrations.CreateModel(
            name='GroundWar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Идёт война')),
                ('round', models.IntegerField(default=0, verbose_name='Раунд войны')),
                ('recon_balance', models.FloatField(default=1, verbose_name='Баланс разведки')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начало войны')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Конец войны')),
                ('agr_dmg', models.BigIntegerField(default=0, verbose_name='Урон - атакующие')),
                ('round_log', models.TextField(blank=True, default='', null=True, verbose_name='Последний раунд')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('hq_points', models.BigIntegerField(default=0, verbose_name='Прочность Штаба')),
                ('agr_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groundwar_agr_region', to='region.region', verbose_name='Регион-агрессор')),
                ('def_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groundwar_def_region', to='region.region', verbose_name='Регион обороняющихся')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Наземная война',
                'verbose_name_plural': 'Наземные войны',
            },
        ),
    ]
