# Generated by Django 3.1.3 on 2023-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0016_auto_20221018_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='infantry',
            name='mines',
            field=models.IntegerField(default=0, verbose_name='Мины'),
        ),
    ]
