# Generated by Django 3.1.3 on 2023-09-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0017_infantry_mines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroundWar',
        ),
    ]
