# Generated by Django 3.1.3 on 2023-09-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0018_delete_groundwar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infantry',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='infantry',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lightvehicle',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lightvehicle',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='recon',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='recon',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='eventwar',
            name='agr_dmg',
        ),
        migrations.RemoveField(
            model_name='eventwar',
            name='recon_balance',
        ),
        migrations.RemoveField(
            model_name='eventwar',
            name='round',
        ),
        migrations.RemoveField(
            model_name='eventwar',
            name='round_log',
        ),
        migrations.RemoveField(
            model_name='warside',
            name='antitank',
        ),
        migrations.RemoveField(
            model_name='warside',
            name='drone',
        ),
        migrations.RemoveField(
            model_name='warside',
            name='ifv',
        ),
        migrations.RemoveField(
            model_name='warside',
            name='rifle',
        ),
        migrations.RemoveField(
            model_name='warside',
            name='tank',
        ),
        migrations.AddField(
            model_name='warside',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Очки урона'),
        ),
        migrations.DeleteModel(
            name='HeavyVehicle',
        ),
        migrations.DeleteModel(
            name='Infantry',
        ),
        migrations.DeleteModel(
            name='LightVehicle',
        ),
        migrations.DeleteModel(
            name='Recon',
        ),
    ]
