# Generated by Django 3.1.3 on 2023-09-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0075_auto_20230914_2245'),
        ('war', '0019_auto_20230926_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField(default=1, verbose_name='Урон')),
                ('energy', models.IntegerField(default=1, verbose_name='Энергии требует')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Юнит',
                'verbose_name_plural': 'Юниты',
            },
        ),
    ]
