# Generated by Django 3.1.3 on 2023-09-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0051_merge_20230715_1629'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('region', '0039_auto_20230909_1643'),
        ('war', '0020_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('damage', models.IntegerField(default=0, verbose_name='Урон')),
                ('energy', models.IntegerField(default=0, verbose_name='Энергии потрачено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Игрок')),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Урон игрока',
                'verbose_name_plural': 'Урон игроков',
            },
        ),
    ]
