# Generated by Django 3.1.3 on 2023-09-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0021_playerdamage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdamage',
            name='region',
        ),
        migrations.AddField(
            model_name='playerdamage',
            name='side',
            field=models.CharField(choices=[('agr', 'Атака'), ('def', 'Оборона')], default='agr', max_length=3),
        ),
    ]
