# Generated by Django 3.1.3 on 2023-10-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0022_auto_20230928_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwar',
            name='round',
            field=models.IntegerField(default=0, verbose_name='Раунд войны'),
        ),
    ]
