# Generated by Django 3.1.3 on 2023-10-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0023_eventwar_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwar',
            name='graph',
            field=models.TextField(blank=True, default='', null=True, verbose_name='График боя'),
        ),
    ]
