# Generated by Django 3.1.3 on 2023-11-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('region', '0042_auto_20231119_0222'),
        ('war', '0024_eventwar_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundWar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='Идёт война')),
                ('round', models.IntegerField(default=0, verbose_name='Раунд войны')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начало войны')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Конец войны')),
                ('graph', models.TextField(blank=True, default='', null=True, verbose_name='График боя')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('hq_points', models.BigIntegerField(default=0, verbose_name='Прочность Штаба')),
                ('agr_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groundwar_agr_region', to='region.region', verbose_name='Регион-агрессор')),
                ('def_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groundwar_def_region', to='region.region', verbose_name='Регион обороняющихся')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Наземная война',
                'verbose_name_plural': 'Наземные войны',
            },
        ),
    ]
