# Generated by Django 3.1.3 on 2023-11-25 18:13

from django.db import migrations

def clear_warside(apps, schema_editor):

    EventWar = apps.get_model("war", "EventWar")
    GroundWar = apps.get_model("war", "GroundWar")

    WarSide = apps.get_model("war", "WarSide")    
    
    EventWar.objects.all().delete()
    GroundWar.objects.all().delete()
    WarSide.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0025_groundwar'),
    ]

    operations = [
        migrations.RunPython(clear_warside),
    ]
