# Generated by Django 3.1.3 on 2023-11-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('war', '0026_auto_20231125_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwar',
            name='end_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventwar_end_task', to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='groundwar',
            name='end_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groundwar_end_task', to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='eventwar',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventwar_round_task', to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='groundwar',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groundwar_round_task', to='django_celery_beat.periodictask'),
        ),
    ]
