# Generated by Django 3.1.3 on 2023-12-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0027_auto_20231126_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwar',
            name='defence_points',
            field=models.BigIntegerField(default=0, verbose_name='Прочность Укрепов'),
        ),
    ]
