# Generated by Django 3.1.3 on 2023-12-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0028_groundwar_defence_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwar',
            name='defence_points',
            field=models.BigIntegerField(default=0, verbose_name='Прочность Укрепов'),
        ),
    ]
