# Generated by Django 3.1.3 on 2024-06-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0057_auto_20240619_2348'),
        ('player', '0081_auto_20240619_2348'),
        ('war', '0029_eventwar_defence_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False, verbose_name='С пропиской')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='Игрок')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Повстанец',
                'verbose_name_plural': 'Повстанцы',
            },
        ),
    ]
