# Generated by Django 3.1.3 on 2024-06-24 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0081_auto_20240619_2348'),
        ('region', '0057_auto_20240619_2348'),
        ('war', '0030_rebel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebel_player', to='player.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='rebel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebel_region', to='region.region', verbose_name='Регион'),
        ),
    ]
