# Generated by Django 3.1.3 on 2024-06-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0031_auto_20240625_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rebel',
            old_name='running',
            new_name='resident',
        ),
    ]
