# Generated by Django 3.1.3 on 2024-06-25 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0032_auto_20240625_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebel',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='rebel',
            name='dtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания записи'),
        ),
    ]
