# Generated by Django 3.2.18 on 2024-07-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    def give_ammo(apps, schema_editor):
        Player = apps.get_model('player', 'Player')
        Storage = apps.get_model('storage', 'Storage')
        Good = apps.get_model('storage', 'Good')
        Stock = apps.get_model('storage', 'Stock')   
        
        
        for player in Player.objects.all():
            cash_add = 0
        
            storages = Storage.objects.filter(owner=player)
            
            for storage in storages:
            
                for good in Good.objects.filter(pk__in=[13, 14, 15, 16, 17, 18, 19, 20]):
                
                    if Stock.objects.filter(storage=storage, good=good).exists():
                
                        stock = Stock.objects.filter(storage=storage, good=good)[0]
                        stock.stock = 10000
                        stock.save()
                    
                    else:
                        stock = Stock(storage=storage, good=good)
                        stock.stock = 10000
                        stock.save()


    dependencies = [
        ('war', '0034_revolution'),
    ]

    operations = [
    ]
