# Generated by Django 3.2.18 on 2024-08-31 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0067_parliament_foundation_date'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('war', '0037_martial'),
    ]

    operations = [
        migrations.AddField(
            model_name='martial',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mar_state', to='state.state', verbose_name='Государство'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='martial',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_beat.periodictask'),
        ),
    ]
