# Generated by Django 3.2.18 on 2024-12-01 15:26

from django.db import migrations
import redis
from war.models.wars.war import War


def process_war_subclasses(apps, schema_editor):
    # Импорт функции get_subclasses
    from player.views.get_subclasses import get_subclasses

    # Получаем все подклассы War
    war_types = get_subclasses(War)

    # Подключение к Redis
    r = redis.StrictRedis(host='redis', port=6379, db=0)

    for war_class in war_types:
        # Для каждого подкласса
        for instance in war_class.objects.filter(running=False):
            # Удаляем ключи из Redis
            r.delete(f'{war_class.__name__}_{instance.pk}_dmg')
            for side in ['agr', 'def']:
                r.delete(f'{war_class.__name__}_{instance.pk}_{side}')


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0038_auto_20240831_2244'),
    ]

    operations = [
        migrations.RunPython(process_war_subclasses),
    ]
